application:
  ignoreDifferences:
    - group: 'kubevirt.io'
      kind: VirtualMachine
      jsonPointers:
      - /spec
    - group: ''
      kind: Secret
      jsonPointers:
      - /spec
  name: "vertica2"
  componentName: Vertica
  componentIndex: 2
  namespace: "default"
source:
  targetRevision: "master"
  path: "vms_argo/helmcharts/vertica"
deploy: false
cluster:
  name: "poc"
  environment: "rnd"
  provider: "openshift"
  region: "telaviv"
  project: "virtualmachines"
  adress: "https://kubernetes.default.svc"
