CONDUCTOR_VIP_PLACEHOLDER: &CONDUCTOR_VIP_PLACEHOLDER conductor-service
SITE_ELASTIC_STORAGE_PLACEHOLDER: &SITE_ELASTIC_STORAGE_PLACEHOLDER hostpath-csi
SITE_HEALTH_STORAGE_PLACEHOLDER: &SITE_HEALTH_STORAGE_PLACEHOLDER hostpath-csi
cs-oam-agent:
  auto-discovery-chart:
    autoDiscovery:
      condcutorDnsName: *CONDUCTOR_VIP_PLACEHOLDER
  elasticsearch-chart:
    data:
      persistence:
        storageClass: *SITE_ELASTIC_STORAGE_PLACEHOLDER
    master:
      persistence:
        storageClass: *SITE_ELASTIC_STORAGE_PLACEHOLDER
  prometheus-operator-chart:
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: *SITE_ELASTIC_STORAGE_PLACEHOLDER
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: *SITE_ELASTIC_STORAGE_PLACEHOLDER
  service-access-config-chart:
    radcomConfiguration:
      conductorIp: *CONDUCTOR_VIP_PLACEHOLDER
      loggerLevel: debug
    legacyConf:
    - name: "kafka"
      type: "kafka"
      port: "9092"
      siteType: "home"
      interface: "oam_direct"
      preferredIp: "v4"
      ipType: "ip"
    - name: "kafka-ext"
      type: "kafka"
      port: "9093"
      siteType: "home"
      interface: "oam_direct"
      ipType: "ip"
    - name: "vertica"
      type: "vertica"
      port: "5433"
      siteType: "home"
      interface: "oam_direct"
      ipType: "ip"
    - name: "vertica-np"
      type: "vertica"
      port: "5433"
      siteType: "primary"
      interface: "oam_direct"
      ipType: "ip"
    - name: "kuberiq-vip"
      type: "kuberiq"
      port: "80"
      siteType: "home"
      interface: "oam_direct"
      ipType: 'vip'
    - name: "kuberiq-np-vip"
      type: "kuberiq"
      port: "80"
      siteType: "primary"
      interface: "oam_direct"
      ipType: 'vip'
    - name: "kuberiq-home-vip"
      type: "kuberiq"
      port: "80"
      siteType: "home"
      interface: "oam_direct"
      ipType: 'vip'
    - name: "conductor-vip"
      type: "conductor"
      port: "80"
      siteType: "primary"
      interface: "oam_direct"
      ipType: 'vip'
    - name: "mongodb"
      type: "mongodb"
      port: "27017"
      siteType: "all"
      interface: "oam_direct"
      ipType: "ip"
    - name: "eventbus-oam-primary"
      type: "kuberiq"
      port: "30201"
      siteType: "primary"
      interface: "oam_direct"
      ipType: 'vip'
    - name: "eventbus-bic-primary"
      type: "kuberiq"
      port: "9092"
      siteType: "primary"
      interface: "oam_direct"
      ipType: "ip"
    - name: "eventbus-traffic-primary"
      type: "kuberiq"
      port: "9094"
      siteType: "primary"
      interface: "oam_direct"
      ipType: 'vip'
    - name: "eventbus-oam-secondary"
      type: "kuberiq"
      port: "30201"
      siteType: "secondary"
      interface: "oam_direct"
    - name: "eventbus-bic-secondary"
      type: "kuberiq"
      port: "9092"
      siteType: "secondary"
      interface: "oam_direct"
      ipType: "ip"
    - name: "eventbus-traffic-secondary"
      type: "kuberiq"
      port: "9094"
      siteType: "secondary"
      interface: "cdr_direct"
      ipType: "ip"
    - name: "kuberiq-primary"
      type: "kuberiq"
      port: "80"
      siteType: "primary"
      interface: "oam_direct"
      ipType: 'vip'
    - name: "kuberiq-secondary"
      type: "kuberiq"
      port: "80"
      siteType: "secondary"
      interface: "oam_direct"
      ipType: 'vip'
    - name: "kuberiq-local"
      type: "kuberiq"
      siteType: "home"
      port: "80"
      interface: "oam_direct"
      ipType: 'vip'

  wait_for_ace_orchestrator: false
shared-templates:
  save_blueprint: true
  wait_for_ace_orchestrator: false
