application:
  name: "aws-nginx-ingress"
  namespace: "default"
target:
  targetRevision: "datavolume-cluster"
  path: "containters/helmcharts/aws-nginx-ingress"
deploy: false
cluster:
  name: in-cluster
  adress: "https://kubernetes.default.svc"