apiVersion: v2
description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery tool for Kubernetes.
name: argo-cd
version: 1.11.1
appVersion: 1.11.1
kubeVersion: ">=1.23.0-0"
dependencies:
  - name: redis-ha
    version: 4.33.8
    repository: https://dandydeveloper.github.io/charts/
    condition: argo-cd.redis-ha.enabled
  - name: argo-cd
    version: 8.3.3
    repository: https://argoproj.github.io/argo-helm
    alias: argo-cd
