{{- if .Values.wait_for_ace_orchestrator_on_post }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-wait-ace-orch-post-hook"
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-wait-ace-orch-post-hook"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      restartPolicy: Never
      containers:
      - name: wait-ace-orch-post-install-job
        image: "{{ .Values.global.docker_registry }}/ace-cd:{{ .Values.ace_cd_tag }}"
        command: ["bash", "ps_tools/argocd/wait_for_ace_orch.sh"]
        env:
        - name: RADCOM_CONDUCTOR_IP
          value: "{{ .Values.global.conductorVip }}"
{{ end }}
