HELM_REGISTRY_PLACEHOLDER: &HELM_REGISTRY_PLACEHOLDER oci://571789434150.dkr.ecr.us-east-2.amazonaws.com
apiVersion: v1
appVersion: '1.0'
dependencies:
- name: cs-oam-agent
  repository: *HELM_REGISTRY_PLACEHOLDER
  version: 1.1001.29
description: cs-oam-agent-cdf
name: cs-oam-agent-cdf
version: 13.09.04