application:
  name: "application-be"
  namespace: "production"
target:
  targetRevision: "marian"
  path: "helmcharts/bp-application-be"
deploy: false
cluster:
  name: cdf
  adress: "https://kubernetes.default.svc"