stream-analytics-manager-chart:
  configMap:
    config_manager_addr: 'configmanager-srv'
    sa_namespace: project-angelfish
  ingresses:
    streamAnalyticsManagerIngress:
      fqdn: project-angelfish.radcom.co.il

stream-analytics-merger-chart:
  configMap:
    config_manager_addr: 'configmanager-srv'
    vertica_user: 'dbadmin'

stream-analytics-renderer-chart:
  configMap:
    kafka_host: 'kafka'

stream-analytics-ui-chart:
  radcomConfiguration:
    streamAnalyticsUiDeployment:
      envs:
        GRAFANA_INGRESS_PATH: "/grafana"
  ingresses:
    streamAnalyticsUiIngress:
      fqdn: project-angelfish.radcom.co.il

stream-analytics-configmaps-chart:
  configMap:
    grafana_secret_name: health-grafana
    grafana_url: health-grafana

probe-core-ms-chart:
  resources:
    limits:
      memory: 6Gi
      cpu: 5000m
      hugepages1Gi: 1
    requests:
      memory: 3Gi
      cpu: 2500m
      hugepages1Gi: 1
  configMap:
    storageClassName: local-storage
    mongoIp: 'mongodb'
  ingresses:
    probe_ingress:
      className: ''
      fqdn: project-angelfish.radcom.co.il
    probe-centralconfig:
      className: ''
      fqdn: project-angelfish.radcom.co.il

kafka-chart:
  fullnameOverride: kafka
  replicaCount: 1
  resources:
    requests:
      cpu: 500m
      memory: 1024Mi
  zookeeper:
    replicaCount: 1

version-data-importer-chart:
  enabled: true
  ingresses:
    versiondataIngress:
      fqdn: project-angelfish.radcom.co.il
      path: /project-angelfish/versiondataimporter(/|$)(.*)

topology-manager-chart:
  radcomConfiguration:
    vaultDataServicePath: "http://secretsms-srv"
  ingresses:
    topologymanagerIngress:
      fqdn: project-angelfish.radcom.co.il
      path: /project-angelfish/topologyManager(/|$)(.*)

radcom-manager-ms-chart:
  radcomConfiguration:
    radcommanagerms:
      useVault: false
  deployments:
    radcommanagermsDeployment:
      containers:
        radcommanagermsContainer:
          configEnvs:
            data:
              type: "data"
              value:
                conductor: "http://topology-manager-srv:8084"
  ingresses:
    radcommanagermsExtapiIngress:
      fqdn: project-angelfish.radcom.co.il
    radcommanagermsIngress:
      fqdn: project-angelfish.radcom.co.il
    radcommanagermsWsIngress:
      fqdn: project-angelfish.radcom.co.il

grafana-helm-chart:
  persistence:
    enabled: false
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/auth-url: null
    ingressClassName: ''
    hosts:
      - project-angelfish.radcom.co.il

config-manager-chart:
  ingresses:
    configmanagerIngress:
      fqdn: project-angelfish.radcom.co.il

vertica-chart:
  ingresses:
    versiondataIngress:
      fqdn: project-angelfish.radcom.co.il
  persistence:
    storageClass: local-storage
  dataBackup:
    enabled: false

mongo-db-chart:
  replicaCount: 1
  replicaSetName: radcom
  image:
    tag: 7.0.5-debian-11-r0
  architecture: replicaset
  persistence:
    storageClass: local-storage
  service:
    nameOverride: mongodb
  auth:
    enabled: true
    rootPassword: 2108a185c5b4969394c9cc18308c72a9
    usernames:
      - orchestration
    passwords:
      - c0146ede83
    databases:
      - admin
  sidecars:
    - name: mongo-init
      image: bitnami/mongodb:8.0.13-debian-12-r0@sha256:2579e968033ec9f97035e91a215a4fb3943eb706eb3871b3d0d1d072e2f45605
      imagePullPolicy: IfNotPresent
      command:
        - /bin/bash
        - '-c'
        - |
          echo "[$(date)] Waiting for MongoDB to be ready..."

          # Wait for MongoDB to be up

          while ! mongosh --eval "print('waiting for connection')" 2>/dev/null; do
            sleep 10
          done

          echo "[$(date)] MongoDB is ready. Starting to grant roles..."

          # Define the MongoDB command to grant roles

          ROLE_COMMAND="db.getSiblingDB('admin').auth('root', '${MONGODB_ROOT_PASSWORD}'); db.getSiblingDB('admin').grantRolesToUser('orchestration', [{role: 'readWrite', db: 'topology' }]);"

          echo "[$(date)] Executing the following MongoDB command: $ROLE_COMMAND"

          mongosh --eval "$ROLE_COMMAND"

          echo "[$(date)] Role assignment completed."
          # sleep for a year
          sleep 31536000
      env:
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cs-system-db-mongo-db-chart
              key: mongodb-root-password
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi

vault-chart:
  server:
    ha:
      replicas: 1
    ingress:
      hosts:
        - host: project-angelfish.radcom.co.il
          paths:
            - /vault(/|$)(.*)
    authDelegator:
      enabled: false

secrets-ms-chart:
  vaultConnectivity:
    vaultHost: vault
    vaultPort: 8200
    vaultSeparator: ":"
  ingresses:
    secretsmsIngress:
      fqdn: project-angelfish.radcom.co.il
