application:
  name: "conductor"
  namespace: "default"
target:
  targetRevision: "eitan"
  path: "helmcharts/Conductor"
deploy: true
cluster:
  name: in-cluster
  adress: "https://kubernetes.default.svc"
