{ 
  "application":
    {   "name": "conductor",
        "namespace": "default"
    },
 "target":
    {
      "targetRevision": "eitan",
       "path": "vms_argo/helmcharts/Conductor"
    },
    "deploy": true,
    "cluster":
     {
       "name": "in-cluster",
       "address": "https://kubernetes.default.svc"
       }
}
