application:
  name: "analyzer-infra"
  namespace: "production"
target:
  targetRevision: "marian"
  path: "helmcharts/analyzer-infra"
deploy: true
cluster:
  name: cdf
  adress: "https://kubernetes.default.svc"