application:
  name: "oam-agent-cdf"
  namespace: "production"
target:
  targetRevision: "marian"
  path: "helmcharts/bp-oam-agent-cdf"
deploy: false
cluster:
  name: cdf
  adress: "https://kubernetes.default.svc"