application:
  name: "ansible-awx-operator"
  namespace: "awx"
source:
  repoURL: "ssh://git@bitbucket-prod.radcom.co.il:7999/devopstools/helmcharts.git"
  targetRevision: "master"
  path: "helmcharts/ansible-awx-operator"
deploy: false
cluster:
  name: "isolation"
  environment: "rnd"
  provider: "vsphere"
  region: "telaviv"
  project: "core"
  adress: "https://kubernetes.default.svc"
