CONDUCTOR_VIP_PLACEHOLDER: &CONDUCTOR_VIP_PLACEHOLDER internal-argocd14RadcomBEALB-783104905.us-east-2.elb.amazonaws.com
DOCKER_REGISTRY: &DOCKER_REGISTRY 692859913461.dkr.ecr.us-east-2.amazonaws.com
MONGO_IP: &MONGO_IP "10.8.33.203"
QROUTER_IP: &QROUTER_IP "10.8.33.247"
SITE_ELASTIC_STORAGE_PLACEHOLDER: &SITE_ELASTIC_STORAGE_PLACEHOLDER gp3
SITE_HEALTH_STORAGE_PLACEHOLDER: &SITE_HEALTH_STORAGE_PLACEHOLDER gp3
NAMESPACE: &NAMESPACE production
CLOUD: &CLOUD aws
VERSION: &VERSION 14.01.00.000.04
SITE_TYPE: &SITE_TYPE national

cs-oam-agent:
  oam-agent-chart:
    enabled: true
  persistence-volume-exporter-chart:
    registry: *DOCKER_REGISTRY
  auto-discovery-chart:
    autoDiscovery:
      condcutorDnsName: *CONDUCTOR_VIP_PLACEHOLDER
  elasticsearch-chart:
    data:
      persistence:
        storageClass: *SITE_ELASTIC_STORAGE_PLACEHOLDER
    master:
      persistence:
        storageClass: *SITE_ELASTIC_STORAGE_PLACEHOLDER
  prometheus-operator-chart:
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: *SITE_ELASTIC_STORAGE_PLACEHOLDER
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: *SITE_ELASTIC_STORAGE_PLACEHOLDER
  service-access-config-chart:
    deployments:
      serviceAccessJob:
        # enabled: true
        annotations: null
    radcomConfiguration:
      conductorIp: *CONDUCTOR_VIP_PLACEHOLDER
      loggerLevel: debug
      # aceOrchestratorSvc: kuberiq-np-vip/orchestrator
      # topologyManagerSvc: kuberiq-np-vip/topologyManager
    autoDiscovery:
      condcutorDnsName: *CONDUCTOR_VIP_PLACEHOLDER
      isLocalFilesAvailable: false
      systemOrchestrationMode: ""
    legacyConf:
    - interface: oam_direct
      ipType: ip
      name: kafka
      port: '9092'
      preferredIp: v4
      siteType: home
      type: kafka
    - interface: oam_direct
      ipType: ip
      name: kafka-ext
      port: '9093'
      siteType: home
      type: kafka
    - interface: oam_direct
      ipType: ip
      name: vertica
      port: '5433'
      siteType: home
      type: vertica
    - interface: oam_direct
      ipType: ip
      name: vertica-np
      port: '5433'
      siteType: primary
      type: vertica
    - interface: oam_direct
      ipType: vip
      name: kuberiq-vip
      port: '80'
      siteType: home
      type: kuberiq
    - interface: oam_direct
      ipType: vip
      name: kuberiq-np-vip
      port: '80'
      siteType: primary
      type: kuberiq
    - interface: oam_direct
      ipType: vip
      name: kuberiq-home-vip
      port: '80'
      siteType: home
      type: kuberiq
    - interface: oam_direct
      ipType: vip
      name: conductor-vip
      port: '80'
      siteType: primary
      type: conductor
    - interface: oam_direct
      ipType: ip
      name: mongodb
      port: '27017'
      siteType: all
      type: mongodb
    - interface: oam_direct
      ipType: vip
      name: eventbus-oam-primary
      port: '30201'
      siteType: primary
      type: kuberiq
    - interface: oam_direct
      ipType: ip
      name: eventbus-bic-primary
      port: '9092'
      siteType: primary
      type: kuberiq
    - interface: oam_direct
      ipType: vip
      name: eventbus-traffic-primary
      port: '9094'
      siteType: primary
      type: kuberiq
    - interface: oam_direct
      name: eventbus-oam-secondary
      port: '30201'
      siteType: secondary
      type: kuberiq
    - interface: oam_direct
      ipType: ip
      name: eventbus-bic-secondary
      port: '9092'
      siteType: secondary
      type: kuberiq
    - interface: cdr_direct
      ipType: ip
      name: eventbus-traffic-secondary
      port: '9094'
      siteType: secondary
      type: kuberiq
    - interface: oam_direct
      ipType: vip
      name: kuberiq-primary
      port: '80'
      siteType: primary
      type: kuberiq
    - interface: oam_direct
      ipType: vip
      name: kuberiq-secondary
      port: '80'
      siteType: secondary
      type: kuberiq
    - interface: oam_direct
      ipType: vip
      name: kuberiq-local
      port: '80'
      siteType: home
      type: kuberiq
  tang-server-chart:
    radcomConfiguration:
      storageClassName: *SITE_ELASTIC_STORAGE_PLACEHOLDER

shared-templates:
  ace_cd_tag: argocd
  update_topology: true
  save_blueprint: false
  wait_for_ace_orchestrator: false