application:
  ignoreDifferences:
    - group: 'kubevirt.io'
      kind: VirtualMachine
      jsonPointers:
      - /spec
    - group: ''
      kind: Secret
      jsonPointers:
      - /spec
  name: "conductor1"
  componentName: Conductor
  componentIndex: 1
  namespace: "default"
source:
  targetRevision: "master"
  path: "helmcharts/virtualmachines/conductor"
deploy: false
cluster:
  name: "poc"
  environment: "rnd"
  provider: "openshift"
  region: "telaviv"
  project: "virtualmachines"
  adress: "https://kubernetes.default.svc"
