application:
  name: "bp-adminapp-be"
  namespace: "default"
  ignoreDifferences:
  - group: "apps"
    kind: "StatefulSet"
    jqPathExpressions:
    - ".spec.volumeClaimTemplates[].apiVersion"
    - ".spec.volumeClaimTemplates[].kind"
  - group: "core"
    kind: "ConfigMap"
    name: "configmap-bp-adminapp-be-nifi-chart"
    namespace: "default"
    jsonPointers:
    - "/data"

target:
  targetRevision: "datavolume-cluster"
  path: "containters/helmcharts/bp-adminapp-be"
deploy: true
cluster:
  name: in-cluster
  adress: "https://kubernetes.default.svc"
