application:
  name: "adminapp-be"
  namespace: "default"
target:
  targetRevision: "eitan"
  path: "containters/helmcharts/adminapp-be"
deploy: true
cluster:
  name: in-cluster
  adress: "https://kubernetes.default.svc"
