{{- define "radcom.secrets.tpl" }}
{{- $enabled := true }}
{{- if eq (kindOf .Values.enabled) "bool"  }}
  {{- $enabled = .Values.enabled }}
{{- end }}
{{- if $enabled }}
{{- $root := . -}}
{{- $namespace := "production" }}
{{- if .Values.global }}
  {{- with .Values.global.namespace }}
    {{- $namespace = . }}
  {{- end }}
{{- end }}
{{- $fullName := include "radcom.fullname" . }}
{{- range $secret := .Values.secrets -}}
{{- $type := "" }}
{{- if $secret.type }}
  {{ $type = tpl $secret.type $root }}
{{- end }}
{{- $typeString := "" }}
{{- if eq $type "Opaque" }}
  {{- $typeString = "Opaque" }}
{{- else if eq $type "token" }}
  {{- $typeString = "bootstrap.kubernetes.io/token" }}
{{- else if (ne $type "") }}
  {{ $typeString = nospace (cat "kubernetes.io/" $type) }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.secretName }}
  namespace: {{ $namespace }}
{{- if $typeString }}
type: {{ $typeString }}
{{- end }}
data:
{{- if and $secret.crt $secret.key }}
  tls.crt: {{ $secret.crt }}
  tls.key: {{ $secret.key }}
{{- else if and $secret.envParam (eq (kindOf $secret.envParam) "map") }}
  {{- tpl (toYaml $secret.envParam) $root | nindent 2 }}
{{- else if $secret.filePath }}
  {{- tpl ($.Files.Get $secret.filePath) $root | nindent 2 }}
{{- end }}
{{- if $secret.stringData }}
stringData:
  {{ tpl (toYaml $secret.stringData) $root | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
