application:
  name: "network-analytics"
  namespace: "default"
target:
  targetRevision: "eitan"
  path: "containters/helmcharts/network-analytics"
deploy: false
cluster:
  name: in-cluster
  adress: "https://kubernetes.default.svc"