cs-automation-infra-cdf:
  automation-infra-chart:
    automationinfraDeployment:
      serviceAccount:
        name: automation-sa
    enabled: false
shared-templates:
  add_blueprints: false
  save_blueprint: false
  wait_for_ace_orchestrator_on_post: true
