cs-event-bus:
  kafka-chart:
    commonLabels:
      blueprintdeployment: '{{ .Release.Name }}'
      blueprinttype: '{{ .Values.global.blueprinttype }}'
      site: '{{ .Values.global.site }}'
      sitetype: '{{ .Values.global.siteType }}'
    controller:
      logPersistence:
        enabled: false
        mountPath: /opt/bitnami/kafka/logs
        size: 8Gi
      persistence:
        enabled: false
        mountPath: /bitnami/kafka
        size: 20Gi
      replicaCount: 3
      resources:
        limits:
          cpu: 500m
          memory: 2048Mi
        requests: {}
    enabled: true
    externalAccess:
      controller:
        service:
          domain: eventbus.primary.com
          ports:
            external: 30202
          type: ClusterIP
      enabled: true
    extraConfig:
      controller.quorum.fetch.timeout.ms: 4000
      controller.quorum.request.timeout.ms: 4000
      defaultReplicationFactor: 3
      deleteTopicEnable: true
      logRetentionBytes: _536870912
      logRetentionCheckIntervalMs: 300000
      logSegmentBytes: _1073741824
      logsDirs: /bitnami/kafka/data
      maxMessageBytes: _104857600
      numPartitions: 1
      offsetsTopicReplicationFactor: 3
    extraEnvVars:
    - name: KAFKA_CFG_LOG_ROLL_HOURS
      value: '1'
    - name: KAFKA_CFG_LOG_RETENTION_MINUTES
      value: '20'
    fullnameOverride: eventbus-kafka
    kraft:
      clusterId: 02AGTQZbRaGWGVECG-8KtA
      enabled: true
    listeners:
      client:
        protocol: PLAINTEXT
      controller:
        protocol: PLAINTEXT
      external:
        protocol: PLAINTEXT
      interbroker:
        protocol: PLAINTEXT
    metrics:
      jmx:
        config: 'jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:5555/jmxrmi

          lowercaseOutputName: true

          lowercaseOutputLabelNames: true

          ssl: false'
        enabled: true
      serviceMonitor:
        enabled: true
    service:
      ports:
        external: 30201
    zookeeper:
      enabled: false
global:
  chartSet: cs-event-bus
  eventbusStorageClass: stc-eventbus
shared-templates:
  add_blueprint: false
