apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.cronjob.name }}-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}