application:
  name: "ingress-nginx"
  namespace: "ingress-nginx"
source:
  repoURL: "ssh://git@bitbucket-prod.radcom.co.il:7999/devopstools/helmcharts.git"
  targetRevision: "master"
  path: "helmcharts/ingress-nginx"
deploy: false
cluster:
  name: "marlin"
  environment: "production"
  provider: "openshift"
  region: "telaviv"
  project: "core"
  adress: "https://kubernetes.default.svc"
