application:
  name: "bp-k8s-infra"
  namespace: "default"
target:
  targetRevision: "datavolume-cluster"
  path: "containters/helmcharts/k8s-infra"
deploy: false
cluster:
  name: in-cluster
  adress: "https://kubernetes.default.svc"