application:
  ignoreDifferences:
    - group: 'kubevirt.io'
      kind: VirtualMachine
      jsonPointers:
      - /spec
    - group: ''
      kind: Secret
      jsonPointers:
      - /spec
  name: "vertica2"  
  componentName: Vertica
  componentIndex: 2
  namespace: "default"
target:
  targetRevision: datavolume-cluster
  path: "vms_argo/helmcharts/Vertica"
deploy: true
cluster:
  name: in-cluster
  address: "https://kubernetes.default.svc"
