Volume_pv_list_0: None
cdf_node_allocation: ''
cdr_direct_net_ip_0: ip_addr
cdr_direct_net_mac: None
cluster_name: Kuberiq_cdf
deploy_default_blueprints: 'False'
kuberiq_cdf_chosen_instance_name: None
kuberiq_cdf_node_count: 1
kuberiq_first_nodes: 'True'
kuberiq_machine_type: Kuberiq
kuberiq_role_etcd: default
kuberiq_role_master: default
kuberiq_role_node: default
kuberiq_role_vault: default
machine_index: 0
machine_type: Kuberiq_cdf
pktinternal_int_net_ip_0: ip_addr
region_site: None
rpm_repo_ip: None
tenant: robin
vnf_name: Kuberiq_CDF
volume_id_0: None
volume_list: None
vprobes_mgmt_int_net_ip_0: ip_addr
vprobes_mgmt_int_net_mac: None
