HELM_REGISTRY_PLACEHOLDER: &HELM_REGISTRY_PLACEHOLDER oci://692859913461.dkr.ecr.us-east-2.amazonaws.com
apiVersion: v1
appVersion: '1.0'
description: event-bus
name: event-bus
version: 14.01.04
dependencies:
- name: cs-event-bus
  repository: *HELM_REGISTRY_PLACEHOLDER
  version: 1.65.0
- name: shared-templates
  version: 1.11.1
  repository: file://../../radcom/shared-templates
