backend_ic_net_ip_0: ip_addr
backend_ic_net_mac: None
machine_index: 0
machine_type: rpmrepository
oam_protected_net_ip_0: ip_addr
oam_protected_net_mac: None
vnf_name: RpmRepository
vprobes_mgmt_int_net_ip_0: ip_addr
vprobes_mgmt_int_net_mac: None
