BLUEPRINT_RAN_PROBE_A: &BLUEPRINT_RAN_PROBE_A "10"
CONDUCTOR_VIP_PLACEHOLDER: &CONDUCTOR_VIP_PLACEHOLDER internal-argocd14RadcomBEALB-783104905.us-east-2.elb.amazonaws.com
DOCKER_REGISTRY: &DOCKER_REGISTRY 692859913461.dkr.ecr.us-east-2.amazonaws.com
MONGO_IP: &MONGO_IP "10.8.33.203"
QROUTER_IP: &QROUTER_IP "10.8.33.247"
SITE_PLACEHOLDER: &SITE_PLACEHOLDER jerus
NAMESPACE: &NAMESPACE production
CLOUD: &CLOUD aws
VERSION: &VERSION 14.01.00.000.04

cs-ran:
  ran-core-ms-chart:
    configMap:
      conductorIp: *CONDUCTOR_VIP_PLACEHOLDER
      mongoIp: *MONGO_IP
      packetMirrorInterfacePref: AWS_RADCOM_PACKET_MIRROR
      qrouterIps: *QROUTER_IP
      siteName: *SITE_PLACEHOLDER
      storageClassName: gp2-persistent
    deployments:
      rancoremsDeployment:
        containers:
          rancoremsContainer:
            envs:
              AWS_RADCOM_CDF_CONTROL_INTF_NAMES: eth0
              AWS_RADCOM_DEFAULT_INTF_NAMES: eth0
              AWS_RADCOM_NF_MANAGER_INTF_NAMES: eth0
              AWS_RADCOM_OAM_DIRECT_INTF_NAMES: eth0
              AWS_RADCOM_PACKET_MIRROR_INTF_NAMES: net1
              AWS_RADCOM_TRAFFIC_DATA_INTF_NAMES: eth0
        podAnnotations:
          k8s.v1.cni.cncf.io/networks: dpdk-net-mirror-ran-10
    services:
      ranprobe-trafficdata:
        externalTrafficPolicy: Cluster
        name: ran-srv-trafficdata-10
        ports:
        - name: trafficdata
          port: 7004
          protocol: TCP
          targetPort: 7004
        sessionAffinity: None
        type: NodePort
    storageClassName: gp2-persistent
global:
  configMap:
    probeId: *BLUEPRINT_RAN_PROBE_A