{
 "title": "FishOS dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
    }
   },
   {
    "name": "node",
    "label": "IP",
    "query": {
     "query": "label_values(node_uname_info{nodename=~\"$hostname\"},instance)"
    }
   },
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(collectd_libvirt_py_cpu_usage{hv_name=~\"$hostname\"},vm_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "graph",
   "description": "collectd_libvirt_py_cpu_usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_libvirt_py_cpu_usage{hv_name=~\"$hostname\",vm_instance=~\"$instance\"}",
     "legendFormat": "{{vm_instance}} @ {{hv_name}}"
    }
   ]
  },
  {
   "title": "CPU usage single",
   "type": "graph",
   "description": "collectd_libvirt_py_cpu_usage_single",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_libvirt_py_cpu_usage_single{hv_name=~\"$hostname\",vm_instance=~\"$instance\"}",
     "legendFormat": "{{vm_instance}} @ {{hv_name}}"
    }
   ]
  },
  {
   "title": "Disk Reads/Writes by instances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "collectd_libvirt_py_read_bw{hv_name=~\"$hostname\",vm_instance=~\"$instance\"}",
     "legendFormat": "{{ vm_instance}} - {{ hv_name }} - Reads"
    },
    {
     "expr": "collectd_libvirt_py_write_bw{hv_name=~\"$hostname\",vm_instance=~\"$instance\"}",
     "legendFormat": "{{ vm_instance}} - {{ hv_name }} - Writes"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "collectd_libvirt_py_memory",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "collectd_libvirt_py_memory{hv_name=~\"$hostname\",vm_instance=~\"$instance\"}",
     "legendFormat": "{{vm_instance}} @ {{hv_name}}"
    }
   ]
  },
  {
   "title": "VM swap",
   "type": "graph",
   "description": "collectd_libvirt_py_vm_swap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "collectd_libvirt_py_vm_swap{hv_name=~\"$hostname\",vm_instance=~\"$instance\"}",
     "legendFormat": "{{vm_instance}} @ {{hv_name}}"
    }
   ]
  },
  {
   "title": "VM port RX bytes/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"tap.+\",hv_name=~\"$hostname\"}[3m])",
     "legendFormat": "{{device}} @ {{hv_name}}"
    }
   ]
  },
  {
   "title": "VM size",
   "type": "graph",
   "description": "collectd_libvirt_py_vm_size",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "collectd_libvirt_py_vm_size{hv_name=~\"$hostname\",vm_instance=~\"$instance\"}",
     "legendFormat": "{{vm_instance}} @ {{hv_name}}"
    }
   ]
  },
  {
   "title": "VM port TX bytes/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"tap.+\"}[3m])",
     "legendFormat": "{{device}} @ {{hv_name}}"
    }
   ]
  }
 ]
}