{
 "title": "OpenStack Exporter",
 "description": "Openstack dashboard using the Openstack Exporter (https://github.com/openstack-exporter/openstack-exporter)",
 "tags": [
  "openstack",
  "openstack-exporter"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_OPENSTACK_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "Source", "query": { "query": "label_values(cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Service status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nova agents down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(openstack_nova_agent_state{adminState=\"enabled\", cluster_name=~\"$Source\"}[1h])) - sum(last_over_time(openstack_nova_agent_state{adminState=\"enabled\", cluster_name=~\"$Source\"}[1h]))"
    }
   ]
  },
  {
   "title": "Nova agent status",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "last_over_time(openstack_nova_agent_state{adminState=\"enabled\", cluster_name=~\"$Source\"}[1h])"
    }
   ]
  },
  {
   "title": "Nova agents up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(openstack_nova_agent_state{adminState=\"enabled\", cluster_name=~\"$Source\"}[1h]))"
    }
   ]
  },
  {
   "title": "Cinder agents down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(openstack_cinder_agent_state{adminState=\"enabled\", cluster_name=~\"$Source\"}[1h])) - sum(last_over_time(openstack_cinder_agent_state{adminState=\"enabled\", cluster_name=~\"$Source\"}[1h]))"
    }
   ]
  },
  {
   "title": "Cinder agent status",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "last_over_time(openstack_cinder_agent_state{cluster_name=~\"$Source\"}[1h])"
    }
   ]
  },
  {
   "title": "Cinder agent up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(openstack_cinder_agent_state{adminState=\"enabled\", cluster_name=~\"$Source\"}[1h]))"
    }
   ]
  },
  {
   "title": "Neutron agents down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(openstack_neutron_agent_state{adminState=\"up\", cluster_name=~\"$Source\"}[1h])) - sum(last_over_time(openstack_neutron_agent_state{adminState=\"up\", cluster_name=~\"$Source\"}[1h]))"
    }
   ]
  },
  {
   "title": "Neutron agent status",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "last_over_time(openstack_neutron_agent_state{cluster_name=~\"$Source\"}[1h])"
    }
   ]
  },
  {
   "title": "Neutron agents up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(openstack_neutron_agent_state{adminState=\"up\", cluster_name=~\"$Source\"}[1h]))"
    }
   ]
  },
  {
   "title": "Resource usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overall CPU cores usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(openstack_nova_vcpus_used{cluster_name=~\"$Source\"})",
     "legendFormat": "used vcpu cores"
    },
    {
     "expr": "sum(openstack_nova_vcpus_available{cluster_name=~\"$Source\"})",
     "legendFormat": "available vcpu cores"
    }
   ]
  },
  {
   "title": "Overall memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(openstack_nova_memory_used_bytes{cluster_name=~\"$Source\"})",
     "legendFormat": "used memory"
    },
    {
     "expr": "sum(openstack_nova_memory_available_bytes{cluster_name=~\"$Source\"})",
     "legendFormat": "available memory"
    }
   ]
  },
  {
   "title": "Keystone projects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(openstack_identity_projects{cluster_name=~\"$Source\"})"
    }
   ]
  },
  {
   "title": "Glance Images",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(openstack_glance_images{cluster_name=~\"$Source\"})"
    }
   ]
  },
  {
   "title": "Nova instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(openstack_nova_total_vms{cluster_name=~\"$Source\"})"
    }
   ]
  },
  {
   "title": "Associated, inactive FIPs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(openstack_neutron_floating_ips_associated_not_active{cluster_name=~\"$Source\"})"
    }
   ]
  },
  {
   "title": "Neutron networks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(openstack_neutron_networks{cluster_name=~\"$Source\"})"
    }
   ]
  },
  {
   "title": "Neutron subnets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(openstack_neutron_subnets{cluster_name=~\"$Source\"})"
    }
   ]
  },
  {
   "title": "Cinder volumes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(openstack_cinder_volumes{cluster_name=~\"$Source\"})"
    }
   ]
  },
  {
   "title": "Cinder snapshots",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(openstack_cinder_snapshots{cluster_name=~\"$Source\"})"
    }
   ]
  },
  {
   "title": "Compute nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU core usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "openstack_nova_vcpus_used{cluster_name=~\"$Source\"} / (openstack_nova_vcpus_available{cluster_name=~\"$Source\"} + openstack_nova_vcpus_used{cluster_name=~\"$Source\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "openstack_nova_memory_used_bytes{cluster_name=~\"$Source\"} / (openstack_nova_memory_used_bytes{cluster_name=~\"$Source\"} + openstack_nova_memory_available_bytes{cluster_name=~\"$Source\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Local storage usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "openstack_nova_local_storage_used_bytes{cluster_name=~\"$Source\"} / (openstack_nova_local_storage_used_bytes{cluster_name=~\"$Source\"} + openstack_nova_local_storage_available_bytes{cluster_name!~\"$Source\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Storage nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Volume pool usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "openstack_cinder_pool_capacity_total_gb{cluster_name=~\"$Source\"} - openstack_cinder_pool_capacity_free_gb{cluster_name=~\"$Source\"} / openstack_cinder_pool_capacity_total_gb{cluster_name=~\"$Source\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Volume pool usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum by(volume_type) (openstack_cinder_volume_gb{cluster_name=~\"$Source\"})",
     "legendFormat": "{{volume_type}}"
    }
   ]
  }
 ]
}