application:
  name: "bp-online-db"
  namespace: "default"
target:
  targetRevision: "datavolume-cluster"
  path: "containters/helmcharts/bp-online-db"
deploy: true
cluster:
  name: in-cluster
  adress: "https://kubernetes.default.svc"
