application:
  name: "aws-nginx-ingress"
  namespace: "production"
target:
  targetRevision: "marian"
  path: "helmcharts/aws-nginx-ingress"
deploy: false
cluster:
  name: cdf
  adress: "https://kubernetes.default.svc"