application:
  name: "packet-analyzer"
  namespace: "production"
target:
  targetRevision: "marian"
  path: "helmcharts/bp-packet-analyzer"
deploy: false
cluster:
  name: cdf
  adress: "https://kubernetes.default.svc"