application:
  name: "ran-probe-a"
  namespace: "production"
target:
  targetRevision: "marian"
  path: "helmcharts/bp-ran-probe-a"
deploy: false
cluster:
  name: cdf
  adress: "https://kubernetes.default.svc"