application:
  ignoreDifferences:
    - group: 'kubevirt.io'
      kind: VirtualMachine
      jsonPointers:
      - /spec
    - group: ''
      kind: Secret
      jsonPointers:
      - /spec
  name: "mongo1"
  componentName: SettingsAndHealthDB
  componentIndex: 1
  namespace: "default"
target:
  targetRevision: datavolume-cluster
  path: "vms_argo/helmcharts/SettingsAndHealthDB"
deploy: false
cluster:
  name: in-cluster
  address: "https://kubernetes.default.svc"
