application:
  name: "bp-application-be"
  namespace: "default"
target:
  targetRevision: "datavolume-cluster"
  path: "containters/helmcharts/bp-application-be"
deploy: true
cluster:
  name: in-cluster
  adress: "https://kubernetes.default.svc"
