application:
  name: "analyzer-infra"
  namespace: "default"
target:
  targetRevision: "eitan"
  path: "containters/helmcharts/bp-analyzer-infra"
deploy: false
cluster:
  name: in-cluster
  adress: "https://kubernetes.default.svc"
