application:
  name: "analyzer-infra"
  namespace: "default"
target:
  targetRevision: "datavolume-cluster"
  path: "containters/helmcharts/bp-analyzer-infra"
deploy: true
cluster:
  name: in-cluster
  adress: "https://kubernetes.default.svc"
