application:
  name: "applications"
  namespace: "production"
target:
  targetRevision: "marian"
  path: "helmcharts/applications"
deploy: true
cluster:
  name: cdf
  adress: "https://kubernetes.default.svc"