application:
  name: "object-storage"
  namespace: "production"
target:
  targetRevision: "marian"
  path: "helmcharts/object-storage"
deploy: true
cluster:
  name: cdf
  adress: "https://kubernetes.default.svc"