enabled: true
global:
  docker_registry: srp.radcom-registry.com:5000
image:
  tag: 1.39.0
  pullPolicy: IfNotPresent
namespace: production
nameOverride: qinsightauth
fullnameOverride: qinsightauth
maxFileUploadSize: 1024m
radcomConfiguration:
  tls: tls-secret
  ipversion: IPv4
deployments:
  qinsightauthDeployment:
    replicas: 1
    containers:
      qinsightauthContainers:
        name: qinsightauth
        image:
          name: qinsight-auth
          tag: '{{ .Values.image.tag }}'
          pullPolicy: '{{ .Values.image.pullPolicy }}'
        livenessProbe:
          failureThreshold: 1
          initialDelaySeconds: 90
          periodSeconds: 60
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 800m
            memory: 512M
          requests:
            cpu: 200m
            memory: 100M
        configFiles:
          podMount: /usr/src/app/config
          files:
            config.json:
              type: file
              path: configMaps/config.json
services:
  qinsightauthService:
    type: ClusterIP
    ports:
    - name: http
      port: 80
      targetPort: 8080
ingresses:
  qinsightauthIngress:
    ingressName: qinsightauth-ing
    serviceName: qinsightauth-srv
    servicePort: 80
    isAuthenticationmsAuth: true
    fqdn: kuberiq.com
    tls_secret: '{{ .Values.radcomConfiguration.tls }}'
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/configuration-snippet: |
        rewrite /(qinsightauth)/(.*)$ /$1//$2 break;
      nginx.ingress.kubernetes.io/proxy-connect-timeout: '300'
      nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: '300'
      nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    path: /qinsightauth
    pathType: Prefix
