application:
  name: "bp-probe"
  namespace: "default"
  ignoreDifferences:
    - group: 'k8s.cni.cncf.io'
      kind: NetworkAttachmentDefinition
      jsonPointers:
      - /spec/config
    - group: 'topology.radcom.com'
      kind: vProbe
      jsonPointers:
      - /spec/customAttributes
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - '.spec.template.spec.containers[] | select(.env[]?.name == "POD_CPU_LIMIT" or .env[]?.name == "POD_CPU_REQUEST" or .env[]?.name == "POD_MEM_REQUEST").env[]?.valueFrom.resourceFieldRef.divisor'
target:
  targetRevision: "datavolume-cluster"
  path: "containters/helmcharts/bp-probe"
deploy: true
cluster:
  name: in-cluster
  adress: "https://kubernetes.default.svc"
