apiVersion: v1
kind: Service
metadata:
  name: conductor-service
spec:
  selector:
    app: conductor
  ports:
    - protocol: TCP
      name: wildfly
      port: 8084
      targetPort: 8084
    - protocol: UDP
      name: ntp
      port: 123
      targetPort: 123
