application:
  name: "bp-oam-agent-cdf"
  namespace: "default"
target:
  targetRevision: "datavolume-cluster"
  path: "containters/helmcharts/oam-agent-cdf"
deploy: false
cluster:
  name: in-cluster
  adress: "https://kubernetes.default.svc"