application:
  name: "ran-probe-b"
  namespace: "production"
target:
  targetRevision: "marian"
  path: "helmcharts/bp-ran-probe-b"
deploy: true
cluster:
  name: cdf
  adress: "https://kubernetes.default.svc"