{{- if index .Values "grafana-mcp" "enabled" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "grafana-mcp-api"
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: "global-secret-store"
    kind: ClusterSecretStore
  target:
    name: "grafana-mcp-api"
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "k0s-tools/monitoring/lgtm/grafana-mcp"
        metadataPolicy: None
        property: api-key
{{- end }}
