CONDUCTOR_VIP_PLACEHOLDER: &CONDUCTOR_VIP_PLACEHOLDER conductor-service
SITE_PLACEHOLDER: &SITE_PLACEHOLDER default
SITE_ELASTIC_STORAGE_PLACEHOLDER: &SITE_ELASTIC_STORAGE_PLACEHOLDER hostpath-csi

cs-probe:
  probe-core-ms-chart:
    conductorIp: *CONDUCTOR_VIP_PLACEHOLDER
    configMap:
      cdfControlInterfacePref: AWS_RADCOM_CDF_CONTROL
      cdfGroup: ''
      defaultInterfacePref: AWS_RADCOM_DEFAULT
      interfaceNames: ''
      nfManagerInterfacePref: AWS_RADCOM_NF_MANAGER
      oamDirectInterfacePref: AWS_RADCOM_OAM_DIRECT
      packetInternalInterfacePref: AWS_RADCOM_PACKET_INTERNAL
      packetMirrorInterfacePref: AWS_RADCOM_PACKET_MIRROR
      qrouterIp: qrouter-0-service
      siteName: *SITE_PLACEHOLDER
      storageClassName: ''
      trafficDataInterfacePref: AWS_RADCOM_TRAFFIC_DATA
      useNetworkAttachmentDefinition: 'no'
      versionNumber: '1.2.3'
    deployments:
      probecoremsDeployment:
        containers:
          probecoremsContainer:
            persistenceVolumes:
            - name: data
              mountPath: /data
              claimName: data-1001
              storageClassName: *SITE_ELASTIC_STORAGE_PLACEHOLDER
                #volumeMode: Filesystem
              accessModes: ReadWriteOnce
              storage: 1Gi
            - name: config
              mountPath: /config
              claimName: config-1001
              storageClassName: *SITE_ELASTIC_STORAGE_PLACEHOLDER
              accessModes: ReadWriteOnce
              storage: 1Gi

            env:
              AWS_RADCOM_CDF_CONTROL_INTF_NAMES: eth1
              AWS_RADCOM_DEFAULT_INTF_NAMES: eth0
              AWS_RADCOM_NF_MANAGER_INTF_NAMES: eth0
              AWS_RADCOM_OAM_DIRECT_INTF_NAMES: eth0
              AWS_RADCOM_PACKET_INTERNAL_INTF_NAMES: eth1
              AWS_RADCOM_TRAFFIC_DATA_INTF_NAMES: eth0
        podAnnotations:
          k8s.v1.cni.cncf.io/networks: dpdk-net-internal-probe-$BLUEPRINT_PROBE_ID
    resources:
      limit:
        cpu: 6000m
        hugepages1Gi: 1
        memory: 8Gi
      requests:
        cpu: 6000m
        hugepages1Gi: 1
        memory: 8Gi
shared-templates:
  add_blueprints: false
  save_blueprint: true
  wait_for_ace_orchestrator: true
