apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-vms
  namespace: openshift-gitops-operator
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=invalid"]
  generators:
  - git:
      repoURL:  https://github.com/eitanbenjam/argocd
      revision: marian
      files:
      - path: 'vms_argo/clusters/**/config.yaml'
  ignoreApplicationDifferences:
    - jsonPointers:
      - /spec/syncPolicy
  template:
    metadata:
      name: '{{.application.name}}' #{{or .application.nameSuffix "" | replace "/" "-"}}'
      labels:
        app.kubernetes.io/component: argocd-vm
        app.kubernetes.io/part-of: '{{.cluster.name}}'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/eitanbenjam/argocd
        targetRevision: '{{.target.targetRevision}}'
        path: '{{.target.path}}'
        helm:
          skipCrds: true
          releaseName: "{{.application.name}}"
          ignoreMissingValueFiles: true
          valueFiles:
            # https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
            - '../general/values.yaml'
            - 'values.yaml'
      destination:
        server: "https://kubernetes.default.svc" #"{{.cluster.address}}"
        namespace: "{{.application.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=false
          - ServerSideDiff=false
        retry:
          limit: 1
  # add template https://github.com/argoproj/argo-cd/issues/17637
  templatePatch: |
    {{- if or .application.syncPolicy.automated }}
    spec:
      {{- if .application.syncPolicy }}
      syncPolicy:
        {{- if .application.syncPolicy.automated }}
        automated:
          {{- if .application.syncPolicy.automated.allowEmpty }}
          allowEmpty: {{ .application.syncPolicy.automated.allowEmpty }}
          {{- end }}
          {{- if .application.syncPolicy.automated.prune }}
          prune: {{ .application.syncPolicy.automated.prune }}
          {{- end }}
          {{- if .application.syncPolicy.automated.selfHeal }}
          selfHeal: {{ .application.syncPolicy.automated.selfHeal}}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  syncPolicy:
    applicationsSync: create-update
