enabled: false
awx-operator:
  AWX:
    # enable use of awx-deploy template
    enabled: true
    name: awx
    spec:
      admin_user: admin
      projects_persistence: true
      projects_storage_access_mode: ReadWriteOnce
      projects_storage_size: 5Gi

      ingress_type: ingress
      # commented out to work in isolation cluster
      #ingress_class_name: "nginx"
      ingress_hosts:
        - hostname: "awx.radcom.co.il"
          tls_secret: wildcard-radcom-co-il-certificate
#        ingress_path: /
      ingress_path_type: Prefix
      ingress_annotations: |
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        kubernetes.io/ingress.class: nginx
      no_log: false
      # Custom secret key stored in AWS secret store in DevOps account Ohio
      secret_key_secret: custom-awx-secret-key

    # configurations for external postgres instance
    postgres:
      enabled: false
      host: Unset
      port: 5678
      dbName: Unset
      username: admin
      # for secret management, pass in the password independently of this file
      # at the command line, use --set AWX.postgres.password
      password: Unset
      sslmode: prefer
      type: unmanaged
libraryChart:
  cronjob:
    name: awx-backup
    schedule: "21 2 * * *"
    image:
      name: postgres
      tag: "15-alpine"
    env:
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: awx-postgres-configuration
            key: password
      - name: PGPASSWORD
        valueFrom:
          secretKeyRef:
            name: awx-postgres-configuration
            key: password
      - name: NEXUS_USER
        valueFrom:
          secretKeyRef:
            name: nexus-credentials
            key: user
      - name: NEXUS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: nexus-credentials
            key: password
    command: ["/bin/sh", "-c"]
    args:
      - |
          set -x && \
          apk add curl && \
          backup_name_tar=awx_data-backup_$(date +%Y_%m_%dT%H_%M).tar && \
          pg_dump -p 5432 -h awx-postgres-15 -U awx -d awx -F t -b -f /tmp/${backup_name_tar} && \
          curl -u admin:admin123 -T /tmp/${backup_name_tar} https://nexus3-prod.radcom.co.il/repository/radcom-files/backups/awx/${backup_name_tar} && \
          echo "Backup and upload completed!"
    restartPolicy: OnFailure
