application:
  name: "probe-lb-agent"
  namespace: "production"
  ignoreDifferences:
    - group: 'k8s.cni.cncf.io'
      kind: NetworkAttachmentDefinition
      jsonPointers:
      - /spec/config
    - group: 'topology.radcom.com'
      kind: vProbe
      jsonPointers:
      - /spec/customAttributes
target:
  targetRevision: "marian"
  path: "helmcharts/bp-probe-lb-agent"
deploy: true
cluster:
  name: cdf
  adress: "https://kubernetes.default.svc"