application:
  name: "probe-lb-agent"
  namespace: "production"
target:
  targetRevision: "marian"
  path: "helmcharts/bp-probe-lb-agent"
deploy: false
cluster:
  name: cdf
  adress: "https://kubernetes.default.svc"