apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "grafana-azuread-credentials"
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: "global-secret-store"
    kind: ClusterSecretStore
  target:
    name: "grafana-azuread-credentials"
    creationPolicy: Owner
  data:
    - secretKey: CLIENT_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "k0s-tools/monitoring/lgtm/sso"
        metadataPolicy: None
        property: CLIENT_ID
    - secretKey: CLIENT_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "k0s-tools/monitoring/lgtm/sso"
        metadataPolicy: None
        property: CLIENT_SECRET
