application:
  name: "external-secrets"
  namespace: "external-secrets"
source:
  repoURL: "ssh://git@bitbucket-prod.radcom.co.il:7999/devopstools/helmcharts.git"
  targetRevision: "master"
  path: "helmcharts/external/external-secrets"
deploy: false
cluster:
  name: "k0stools"
  environment: "production"
  provider: "vsphere"
  region: "telaviv"
  project: "core"
  adress: "https://kubernetes.default.svc"
