application:
  name: "admin-applications"
  namespace: "default"
target:
  targetRevision: "eitan"
  path: "containters/helmcharts/bp-admin-applications"
deploy: false
cluster:
  name: in-cluster
  adress: "https://kubernetes.default.svc"
