application:
  name: "admin-applications"
  namespace: "production"
target:
  targetRevision: "marian"
  path: "helmcharts/bp-admin-applications"
deploy: true
cluster:
  name: cdf
  adress: "https://kubernetes.default.svc"