cs-k8s-infra:
  aws-ingress-nginx-chart:
    enabled: false
  maveriq-dns-chart:
    enabled: false
  multus-chart:
    enabled: false
  persistence-volume-provisioner-chart:
    enabled: false
  radcom-crds-chart:
    enabled: false
  radcom-ingress-nginx-chart:
    controller:
      admissionWebhooks:
        patch:
          image:
            digest: false
            registry: nexus3-prod.radcom.co.il:8084
      hostNetwork: false
      image:
        digest: false
        registry: nexus3-prod.radcom.co.il:8084
      publishService:
        enabled: false
      service:
        enabled: true
        externalTrafficPolicy: Local
        type: LoadBalancer
        nodePorts:
          https: 30443
          http: 30080
        annotations:
          metallb.universe.tf/address-pool: openshiftpoc-ip-pools
    enabled: true
    tcp: {}
    udp: {}
shared-templates:
  add_blueprints: false
  save_blueprint: false
  wait_for_ace_orchestrator: false
