DOCKER_REGISTRY_PLACEHOLDER: &DOCKER_REGISTRY_PLACEHOLDER 571789434150.dkr.ecr.us-east-2.amazonaws.com
cs-k8s-infra:
  maveriq-dns-chart:
    enabled: false
  multus-chart:
    enabled: false
  persistence-volume-provisioner-chart:
    enabled: false
  radcom-crds-chart:
    enabled: true
  radcom-ingress-nginx-chart:
    enabled: false
shared-templates:
  add_blueprints: false
  wait_for_ace_orchestrator: false
