{{- if .Values.clusterSecretStore }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: global-secret-store
spec:
  provider:
    {{- if .Values.clusterSecretStore.aws }}
    aws:
      service: SecretsManager
      region: {{ .Values.clusterSecretStore.aws.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-iam-secret
            key: access-key
            namespace: "external-secrets"
          secretAccessKeySecretRef:
            name: aws-iam-secret
            key: secret-access-key
            namespace: "external-secrets"
    {{- end }}
{{- end }}
