application:
  name: "probe"
  namespace: "production"
  ignoreDifferences:
    # - group: 'k8s.cni.cncf.io'
    #   kind: NetworkAttachmentDefinition
    # - group: 'topology.radcom.com'
    #   kind: vProbe
    # - group: apps
    #   kind: StatefulSet
    #   jqPathExpressions:
    #     - '.spec.template.spec.containers[] | select(.env[]?.name == "POD_CPU_LIMIT" or .env[]?.name == "POD_CPU_REQUEST" or .env[]?.name == "POD_MEM_REQUEST").env[]?.valueFrom.resourceFieldRef.divisor'
  targetRevision: "marian"
  path: "helmcharts/bp-probe"
deploy: false
cluster:
  name: cdf
  adress: "https://kubernetes.default.svc"