application:
  name: "probe"
  namespace: "production"
  ignoreApplicationDifferences:
    group: 'k8s.cni.cncf.io/v1'
    kind: NetworkAttachmentDefinition
    # group: apps
    # kind: StatefulSet
    # jqPathExpressions:
    #   - '.spec.template.spec.containers[] | select(.name == "POD_CPU_LIMIT" or .name == "POD_CPU_REQUEST" or .name == "POD_MEM_REQUEST").valueFrom.resourceFieldRef.divisor'
target:
  targetRevision: "marian"
  path: "helmcharts/bp-probe"
deploy: true
cluster:
  name: cdf
  adress: "https://kubernetes.default.svc"