{{- if .Values.enabled }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: blueprints.extensions.example.com
spec:
  group: extensions.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                 deploymentName:
                   type: string
                 blueprintType:
                   type: string
                 blueprintVersion:
                   type: string
                 restartOnDeploy:
                   type: boolean
                 chartSetName:
                   type: string
                 chartSetVersion:
                   type: string
                 bpConfigurationFileName:
                   type: string
                 bpConfigurationName:
                   type: string
                 bpConfigurationRevision:
                   type: string
                 bpConfigurationAttributes:
                   type: object
                   x-kubernetes-preserve-unknown-fields: true
                 bpDeploymentAttributes:
                   type: object
                   x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: blueprints
    singular: blueprint
    kind: Blueprint
    shortNames:
      - bp
{{- end }}
