cs-ran:
  ran-core-ms-chart:
    cdrPVC:
      storageSize: 2Gi
    configMap:
      clusterName: RAN
      machineType: RAN-probe-a
      name: ranProbe-a
      networkIpMode: ipv4
      trafficMirrorNetworkGateway: ''
    resources:
      limits:
        cpu: 10000m
        hugepages1Gi: 1
        memory: 8Gi
      requests:
        cpu: 10000m
        hugepages1Gi: 1
        memory: 8Gi
    storagePVC:
      storageSize: 20Gi
global:
  configMap:
    probeId: '10'
shared-templates:
  add_blueprints: false
  save_blueprint: false
  wait_for_ace_orchestrator: false
