application:
  name: "monitoring-tools"
  namespace: "default"
target:
  targetRevision: "eitan"
  path: "containters/helmcharts/monitoring-tools"
deploy: false
cluster:
  name: in-cluster
  adress: "https://kubernetes.default.svc"