application:
  name: "ran-probe-a"
  namespace: "default"
target:
  targetRevision: "datavolume-cluster"
  path: "containters/helmcharts/ran-probe-a"
deploy: false
cluster:
  name: in-cluster
  adress: "https://kubernetes.default.svc"