global:
  conductorVip: 1.2.3.4
  namespace: production
  dockerRegistry: localhost:5000
  site: telaviv
  maveriq_version: 13.09.00.000.00

replicas: 1   # for deployment
pullPolicy: Always
node_port: 32142
env_id: radcom
source_control: "configmap"  # can be s3:// , configmap, http:// , file://  
srp_ip: None
ansible_check: yes
install_http_service: false
build_helm_repository: true


kuberiq_cluster_name: Kuberiq
kuberiq_type: kuberiq_cdf
site_type: national # cdf


create_cluster_role: true
cronjob_name: false

resources:
  limits:
    cpu: '500m'
    memory: '512M'

cloud:
  type: aws
  robin_extra_params:
    robin_server_ip: 2001:1:2:3::4
    robin_server_username: admin
    robin_server_password: Radmin1
  aws_extra_params:
    service_account_name: cicd-cluster-eks-role
    arn_role: "arn:aws:iam::XXXXXXX:role:radcom/-eks-role"
image:
  tag: latest
  helm_repository_tag: latest
