add_default_sa_prometheus_permissions: true
ingress:
  enabled: true
  service:
    externalTrafficPolicy: Local
    type: LoadBalancer
    annotations:
      metallb.universe.tf/address-pool: openshiftpoc-ip-pools

