application:
  name: "monitoring-tools"
  namespace: "production"
target:
  targetRevision: "marian"
  path: "helmcharts/monitoring-tools"
deploy: true
cluster:
  name: cdf
  adress: "https://kubernetes.default.svc"