apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: bp-oam-agent-region
  name: bp-oam-agent-region
  namespace: argocd
spec:
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 10
  sources:
  - helm:
      ignoreMissingValueFiles: false
      valueFiles:
      - blueprint_value/conf-region-oam-agent.yaml
      - ../general/values.yaml
      - values.yaml
      version: v3
    path: applications/bp-oam-agent-region
    ref: my-repo
    repoURL: https://github.com/eitanbenjam/argocd
    targetRevision: marian
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      annotations:
        annotations: on-the-namespace
        applies: for
        the: same
      labels:
        any: label
        you: like
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
