CONDUCTOR_VIP_PLACEHOLDER: &CONDUCTOR_VIP_PLACEHOLDER 172.29.170.103
SITE_ELASTIC_STORAGE_PLACEHOLDER: &SITE_ELASTIC_STORAGE_PLACEHOLDER local-storage
SITE_HEALTH_STORAGE_PLACEHOLDER: &SITE_HEALTH_STORAGE_PLACEHOLDER local-storage
shared-templates:
  wait_for_ace_orchestrator: false
  wait_for_ace_orchestrator_on_post: true
  add_blueprints: true
cs-oam-agent:
  
  wait_for_ace_orchestrator: false
  service-access-config-chart:
    radcomConfiguration:
      conductorIp: *CONDUCTOR_VIP_PLACEHOLDER
  auto-discovery-chart:
    autoDiscovery:
      condcutorDnsName: *CONDUCTOR_VIP_PLACEHOLDER
  elasticsearch-chart:
    master:
      persistence:
        storageClass: *SITE_ELASTIC_STORAGE_PLACEHOLDER
    data:
      persistence:
        storageClass: *SITE_ELASTIC_STORAGE_PLACEHOLDER
  prometheus-operator-chart:
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: *SITE_HEALTH_STORAGE_PLACEHOLDER
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: *SITE_HEALTH_STORAGE_PLACEHOLDER
