CONDUCTOR_VIP_PLACEHOLDER: 172.29.170.103
SITE_ELASTIC_STORAGE_PLACEHOLDER: local-storage
SITE_HEALTH_STORAGE_PLACEHOLDER: local-storage
chartsetConfigurationName: conf-region-oam-agent.yaml
cs-oam-agent:
  auto-discovery-chart:
    autoDiscovery:
      condcutorDnsName: 172.29.170.103
  elasticsearch-chart:
    data:
      persistence:
        storageClass: local-storage
    master:
      persistence:
        storageClass: local-storage
  prometheus-operator-chart:
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: local-storage
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-storage
  service-access-config-chart:
    radcomConfiguration:
      conductorIp: 172.29.170.103
  wait_for_ace_orchestrator: false
shared-templates:
  save_blueprint: true
  wait_for_ace_orchestrator: false
