application:
  name: "session-analyzer"
  namespace: "production"
target:
  targetRevision: "marian"
  path: "helmcharts/session-analyzer"
deploy: false
cluster:
  name: cdf
  adress: "https://kubernetes.default.svc"