application:
  name: "adminapp-be"
  namespace: "production"
target:
  targetRevision: "marian"
  path: "helmcharts/adminapp-be"
deploy: false
cluster:
  name: cdf
  adress: "https://kubernetes.default.svc"