application:
  name: "packet-analyzer"
  namespace: "production"
source:
  repoURL: "ssh://git@3.12.180.20/radcom/helmcharts.git"
  targetRevision: "master"
  path: "helmcharts/radcom/packet-analyzer"
deploy: true
cluster:
  provider: "aws"
  region: "us-east-2"
  name: "cdf"
  environment: "rnd"
  project: "be"
  adress: "https://AC7149A00FBB8E4EFBC7B78C9318A9C5.gr7.us-east-2.eks.amazonaws.com"
