application:
  name: "ingress-nginx"
  namespace: "ingress-nginx"
source:
  repoURL: "ssh://git@bitbucket-prod.radcom.co.il:7999/devopstools/helmcharts.git"
  targetRevision: "master"
  path: "helmcharts/radcom/radcom-ingress-nginx"
deploy: true
cluster:
  name: isolation
  environment: "rnd"
  provider: vsphere
  region: "telaviv"
  project: "core"
  adress: "https://kubernetes.default.svc"
