application:
  name: "bp-session-analyzer"
  namespace: "default"
target:
  targetRevision: "eitan"
  path: "containters/helmcharts/bp-session-analyzer"
deploy: true
cluster:
  name: in-cluster
  adress: "https://kubernetes.default.svc"
