application:
  name: "probe-lb"
  namespace: "production"
target:
  targetRevision: "marian"
  path: "helmcharts/probe-lb"
deploy: false
cluster:
  name: cdf
  adress: "https://kubernetes.default.svc"