application:
  name: "k8s-infra-cdf"
  namespace: "production"
target:
  targetRevision: "marian"
  path: "helmcharts/bp-k8s-infra-cdf"
deploy: true
cluster:
  name: cdf
  adress: "https://kubernetes.default.svc"