apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=invalid"]
  generators:
    - git:
        repoURL:  https://github.com/eitanbenjam/argocd
        revision: marian
        files:
          - path: 'clusters/**/config.yaml'
      selector:
        matchExpressions:
          - key: deploy
            operator: In
            values:
              - "true"
          - key: cluster.name
            operator: In
            values:
              # Set the enviroment to where you want to deploy. Take notice not to apply to a difrent cluster than intended
              - "cdf"
  template:
    metadata:
      name: '{{.application.name}}{{or .application.nameSuffix "" | replace "/" "-"}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/eitanbenjam/argocd
        targetRevision: '{{.target.targetRevision}}'
        path: '{{.target.path}}'
        helm:
          skipCrds: true
          releaseName: "{{.application.name}}"
          valueFiles:
            # https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
            - '../general/values.yaml'
            - 'values.yaml'
            - '../../clusters/{{.cluster.name}}/{{.application.name}}{{or .application.nameSuffix "" }}/values.yaml'
      destination:
        name: "{{.cluster.name}}"
        namespace: "{{.application.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - ServerSideDiff=true
        retry:
          limit: 2
  # add template https://github.com/argoproj/argo-cd/issues/17637
  templatePatch: |
    {{- if or .application.ignoreDifferences .application.syncPolicy.automated }}
    spec:
      {{- if .application.ignoreDifferences }}
      ignoreDifferences:
        - group: {{ .application.ignoreDifferences.group }}
          kind: {{ .application.ignoreDifferences.kind }}
          jqPathExpressions:
            - {{ .application.ignoreDifferences.jqPathExpressions }}
      {{- end }}
      {{- if .application.ignoreApplicationDifferences }}
      ignoreApplicationDifferences:
        - jsonPointers:
          - {{ .application.IgnoreApplicationDifference.jsonPointers }}
      {{- end }}
      {{- if .application.syncPolicy }}
      syncPolicy:
        {{- if .application.syncPolicy.automated }}
        automated:
          {{- if .application.syncPolicy.automated.allowEmpty }}
          allowEmpty: {{ .application.syncPolicy.automated.allowEmpty }}
          {{- end }}
          {{- if .application.syncPolicy.automated.prune }}
          prune: {{ .application.syncPolicy.automated.prune }}
          {{- end }}
          {{- if .application.syncPolicy.automated.selfHeal }}
          selfHeal: {{ .application.syncPolicy.automated.selfHeal}}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  syncPolicy:
    applicationsSync: create-update