cs-adminapp-be:
  nifi-chart:
    radcomConfiguration:
      nifiserver:
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 1
            memory: 1Gi

    persistence:
      storageClass: hostpath-csi
shared-templates:
  add_blueprints: false
  save_blueprint: true
  wait_for_ace_orchestrator_on_post: true
