apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-ace-cd-task
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: configmap-ace-cd-task
data:
  env_id:  {{ .Values.env_id }}
  conductor_ip:  {{ .Values.global.conductorVip }}
  srp_ip:  {{ .Values.srp_ip }}
  source_control: {{ .Values.source_control }}
  site: {{ .Values.global.site }}
  ansible_check: "{{ .Values.ansible_check }}"
  upgrade_repo: "{{ .Values.upgrade_repo }}"
  upgrade_version: "{{ .Values.upgrade_version }}"
  maveriq_version: "{{ .Values.global.maveriq_version }}"
  kuberiq_cluster_name: "{{ .Values.kuberiq_cluster_name }}"
  kuberiq_type: "{{ .Values.kuberiq_type }}"
  site_type: "{{ .Values.site_type }}"
  cloud: "{{ .Values.cloud.type }}"
  {{- if eq .Values.cloud.type "robin"}}
  robin_server: "{{ .Values.cloud.robin_extra_params.robin_server_ip }}"
  robin_server_password: "{{ .Values.cloud.robin_extra_params.robin_server_password }}"
  robin_server_username: "{{ .Values.cloud.robin_extra_params.robin_server_username }}"
  {{- end }}
