{{- if or (eq .Values.cloud.type "aws") (eq .Values.cloud.type "local")}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.cloud.aws_extra_params.service_account_name }}"
  namespace: {{ .Values.global.namespace }}
  {{- if or (eq .Values.cloud.type "aws")}}
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.cloud.aws_extra_params.arn_role }}"
  {{ end }}
{{ end }}
