application:
  ignoreDifferences:
    - group: 'kubevirt.io'
      kind: VirtualMachine
      jsonPointers:
      - /spec
    - group: ''
      kind: Secret
      jsonPointers:
      - /spec
  name: "vertica0"
  namespace: "default"
  componentName: Vertica
target:
  targetRevision: "datavolume-cluster"
  path: "vms_argo/helmcharts/Vertica0"
deploy: false
cluster:
  name: in-cluster
  address: "https://kubernetes.default.svc"
