application:
  name: "sonarqube"
  namespace: "sonarqube"
  ignoreDifferences:
    - group: "apps"
      kind: "StatefulSet"
      jqPathExpressions:
        - ".spec.volumeClaimTemplates[].apiVersion"
        - ".spec.volumeClaimTemplates[].kind"
source:
  repoURL: "ssh://git@bitbucket-prod.radcom.co.il:7999/devopstools/helmcharts.git"
  targetRevision: "master"
  path: "helmcharts/external/sonarqube"
deploy: true
cluster:
  name: "k0stools"
  environment: "rnd"
  provider: "vsphere"
  region: "telaviv"
  project: "core"
  adress: "https://kubernetes.default.svc"
