CONDUCTOR_VIP_PLACEHOLDER: &CONDUCTOR_VIP_PLACEHOLDER internal-argoRadcomBEALB-674568957.us-east-2.elb.amazonaws.com
SITE_ELASTIC_STORAGE_PLACEHOLDER: &SITE_ELASTIC_STORAGE_PLACEHOLDER gp3
SITE_HEALTH_STORAGE_PLACEHOLDER: &SITE_HEALTH_STORAGE_PLACEHOLDER gp3

cs-oam:
  ggsn-distribution-ms-chart:
    services:
      ggsnDistributionMsActuatorService:
        ports:
          - port: 80
            targetPort: 8085
            name: http-actuator
  config-distribution-chart:
    services:
      configDistributionActuatorService:
        ports:
          - port: 80
            targetPort: 8085
            name: http-actuator
  oam-agent-chart:
    enabled: false

shared-templates:
  add_blueprints: true
  save_blueprint: true
  wait_for_ace_orchestrator: false
  wait_for_ace_orchestrator_on_post: true
  # wait_for_event_bus: true
