cs-oam:
  ggsn-distribution-chart:
    services:
      ggsnDistributionMsActuatorService:
        ports:
          - port: 80
            targetPort: 8085
            name: http-actuator

  config-distribution-chart:
    services:
      configDistributionService:
        ports:
          - port: 80
            targetPort: 8085
            name: http-actuator

shared-templates:
  add_blueprints: true
  save_blueprint: true
  wait_for_ace_orchestrator: false
  wait_for_ace_orchestrator_on_post: true
  # wait_for_event_bus: true
