CONDUCTOR_VIP_PLACEHOLDER: &CONDUCTOR_VIP_PLACEHOLDER internal-argoRadcomBEALB-674568957.us-east-2.elb.amazonaws.com
SITE_ELASTIC_STORAGE_PLACEHOLDER: &SITE_ELASTIC_STORAGE_PLACEHOLDER gp3
SITE_HEALTH_STORAGE_PLACEHOLDER: &SITE_HEALTH_STORAGE_PLACEHOLDER gp3

cs-oam:
  ggsn-distribution-ms-chart:
    services:
      ggsnDistributionMsActuatorService:
        ports:
          - port: 80
            targetPort: 8085
            name: http-actuator
  config-distribution-chart:
    services:
      configDistributionActuatorService:
        ports:
          - port: 80
            targetPort: 8085
            name: http-actuator
  oam-agent-chart:
    enabled: false
  service-access-config-chart:
    autoDiscovery:
      condcutorDnsName: *CONDUCTOR_VIP_PLACEHOLDER
      isLocalFilesAvailable: false
      systemOrchestrationMode: ""
    legacyConf:
    - interface: oam_direct
      ipType: ip
      name: kafka
      port: "9092"
      preferredIp: v4
      siteType: home
      type: kafka
    - interface: oam_direct
      ipType: ip
      name: kafka-ext
      port: "9093"
      siteType: home
      type: kafka
    - interface: oam_direct
      ipType: ip
      name: vertica
      port: "5433"
      siteType: home
      type: vertica
    - interface: oam_direct
      ipType: ip
      name: vertica-np
      port: "5433"
      siteType: primary
      type: vertica
    - interface: oam_direct
      ipType: vip
      name: kuberiq-vip
      port: "80"
      siteType: home
      type: kuberiq
    - interface: oam_direct
      ipType: vip
      name: kuberiq-np-vip
      port: "80"
      siteType: primary
      type: kuberiq
    - interface: oam_direct
      ipType: vip
      name: kuberiq-home-vip
      port: "80"
      siteType: home
      type: kuberiq
    - interface: oam_direct
      ipType: vip
      name: conductor-vip
      port: "80"
      siteType: primary
      type: conductor
    - interface: oam_direct
      ipType: ip
      name: mongodb
      port: "27017"
      siteType: all
      type: mongodb
    - interface: oam_direct
      ipType: vip
      name: eventbus-oam-primary
      port: "30201"
      siteType: primary
      type: kuberiq
    - interface: oam_direct
      ipType: ip
      name: eventbus-bic-primary
      port: "9092"
      siteType: primary
      type: kuberiq
    - interface: oam_direct
      ipType: vip
      name: eventbus-traffic-primary
      port: "9094"
      siteType: primary
      type: kuberiq
    - interface: oam_direct
      name: eventbus-oam-secondary
      port: "30201"
      siteType: secondary
      type: kuberiq
    - interface: oam_direct
      ipType: ip
      name: eventbus-bic-secondary
      port: "9092"
      siteType: secondary
      type: kuberiq
    - interface: cdr_direct
      ipType: ip
      name: eventbus-traffic-secondary
      port: "9094"
      siteType: secondary
      type: kuberiq
    - interface: oam_direct
      ipType: vip
      name: kuberiq-primary
      port: "80"
      siteType: primary
      type: kuberiq
    - interface: oam_direct
      ipType: vip
      name: kuberiq-secondary
      port: "80"
      siteType: secondary
      type: kuberiq
    - interface: oam_direct
      ipType: vip
      name: kuberiq-local
      port: "80"
      siteType: home
      type: kuberiq

shared-templates:
  add_blueprints: true
  save_blueprint: true
  wait_for_ace_orchestrator: false
  wait_for_ace_orchestrator_on_post: true
  # wait_for_event_bus: true
