HELM_REGISTRY_PLACEHOLDER: &HELM_REGISTRY_PLACEHOLDER oci://571789434150.dkr.ecr.us-east-2.amazonaws.com
apiVersion: v1
appVersion: '1.0'
description: aws-nginx-ingress
name: aws-nginx-ingress
version: 1.375.0
dependencies:
  - name: cs-k8s-infra
    version: 1.99.0
    repository:  *HELM_REGISTRY_PLACEHOLDER



