HELM_REGISTRY_PLACEHOLDER: &HELM_REGISTRY_PLACEHOLDER oci://692859913461.dkr.ecr.us-east-2.amazonaws.com
apiVersion: v2
description: A Helm chart for management-etl.
name: "management-etl"
version: 1.11.1
appVersion: 1.11.1
kubeVersion: ">=1.23.0-0"
dependencies:
  - name: radcom-manager-ms
    version: 1.394.0
    repository: *HELM_REGISTRY_PLACEHOLDER
  - name: topology-manager
    version: 1.158.0
    repository: *HELM_REGISTRY_PLACEHOLDER
  - name: daemon
    version: 1.523.0
    repository: *HELM_REGISTRY_PLACEHOLDER
  - name: database-loader
    version: 1.437.0
    repository: *HELM_REGISTRY_PLACEHOLDER
  - name: enrichment-autoloader
    version: 1.60.0
    repository: *HELM_REGISTRY_PLACEHOLDER
  - name: enrichment-loader-ms
    version: 1.223.0
    repository: *HELM_REGISTRY_PLACEHOLDER
  - name: ne-loader-ms
    version: 1.230.0
    repository: *HELM_REGISTRY_PLACEHOLDER
  - name: network-element-autoloader
    version: 1.62.0
    repository: *HELM_REGISTRY_PLACEHOLDER
  - name: schema-builder
    version: 1.476.0
    repository: *HELM_REGISTRY_PLACEHOLDER
  - name: maveriq-config-ms
    version: 1.199.0
    repository: *HELM_REGISTRY_PLACEHOLDER
  - name: system-db-ms
    version: 1.67.0
    repository: *HELM_REGISTRY_PLACEHOLDER
  - name: config-manager
    version: 1.85.0
    repository: *HELM_REGISTRY_PLACEHOLDER
  - name: vertica
    version: 1.20.0
    repository: *HELM_REGISTRY_PLACEHOLDER
  - name: kafka
    version: 1.29.0
    repository: *HELM_REGISTRY_PLACEHOLDER
  - name: mongo-db
    version: 1.0.0
    repository: *HELM_REGISTRY_PLACEHOLDER
  - name: automation-infra
    version: 1.888.0
    repository: *HELM_REGISTRY_PLACEHOLDER
  - name: version-data-importer
    version: 1.33.0
    repository: *HELM_REGISTRY_PLACEHOLDER
