HELM_REGISTRY_PLACEHOLDER: &HELM_REGISTRY_PLACEHOLDER oci://571789434150.dkr.ecr.us-east-2.amazonaws.com
apiVersion: v1
appVersion: '1.0'
dependencies:
- name: cs-application-be
  repository: *HELM_REGISTRY_PLACEHOLDER
  version: 1.805.12
description: bp-application-be
name: bp-application-be
version: 13.09.04