application:
  name: "oam-agent"
  namespace: "default"
target:
  targetRevision: "eitan"
  path: "containters/helmcharts/bp-oam-agent"
deploy: false
cluster:
  name: in-cluster
  adress: "https://kubernetes.default.svc"
