application:
  ignoreDifferences:
    - group: 'kubevirt.io'
      kind: VirtualMachine
      jsonPointers:
      - /spec
    - group: ''
      kind: Secret
      jsonPointers:
      - /spec
  name: "conductor1"
  namespace: "default"
target:
  targetRevision: "datavolume-cluster"
  path: "vms_argo/helmcharts/Conductor1"
deploy: false
cluster:
  name: in-cluster
  address: "https://kubernetes.default.svc"
