application:
  ignoreDifferences:
    - group: 'kubevirt.io'
      kind: VirtualMachine
      jsonPointers:
      - /spec
    - group: ''
      kind: Secret
      jsonPointers:
      - /spec
  name: "processing0"
  componentName: Processing
  componentIndex: 0
  namespace: "default"
target:
  targetRevision: datavolume-cluster
  path: "vms_argo/helmcharts/Processing"
deploy: false
cluster:
  name: in-cluster
  address: "https://kubernetes.default.svc"
