HELM_REGISTRY_PLACEHOLDER: &HELM_REGISTRY_PLACEHOLDER http://nexus3-prod.radcom.co.il:8081/repository/charts/
apiVersion: v1
appVersion: '1.0'
dependencies:
- name: cs-admin-applications
  repository: *HELM_REGISTRY_PLACEHOLDER
  version: 1.560.0
- name: shared-templates
  repository: *HELM_REGISTRY_PLACEHOLDER
  version: 1.0.0
description: bp-admin-applications
name: bp-admin-applications
version: 13.09.04