shared-templates:
  add_blueprints: false
  save_blueprint: true
  wait_for_ace_orchestrator_on_post: true


cs-admin-applications:
  grafana-helm-chart:
    persistence:
      storageClass: XXX
      storageClassName: XXX


