{{- define "radcom.services.tpl" }}
{{- if .Values.services }}
{{- $name := include "radcom.name" . }}
{{- $fullName := include "radcom.fullname" . }}
{{- $enabled := true }}
{{- $chartName :=  include "radcom.chart" . }}
{{- $releaseName := .Release.Name }}
{{- $chartAppVersion := .Chart.AppVersion}}
{{- $releaseService := .Release.Service }}
{{- $selectorLabels := include "radcom.selectorLabels" . }}
{{- if eq (kindOf .Values.enabled) "bool"  }}
  {{- $enabled = .Values.enabled }}
{{- end }}
{{- if $enabled }}
{{- $namespace := "production" }}
{{- $serviceType := "ClusterIP" }}
{{- $serviceAnnotations := "" }}
{{- $loadBalancerSourceRanges := "" }}
{{- if .Values.global }}
  {{- with .Values.global.namespace }}
    {{- $namespace = . }}
  {{- end }}
{{- end }}
{{- $root := . -}}
{{- range $currService := .Values.services -}}
{{- $serviceName := (printf "%s-%s" $fullName "srv") }}
{{- if $currService.name }}
  {{- with $currService.name }}
    {{- $serviceName = tpl ($currService.name) $root}}
  {{- end }}
{{- end }}
{{- $nodePort := "" }}
{{- $ports := dict "ports" $currService.ports }}
{{- with $currService.type }}
  {{- $serviceType = tpl . $root }}
{{- end }}
{{- with $currService.annotations }}
  {{- $serviceAnnotations = . }}
{{- end }}
{{- with $currService.loadBalancerSourceRanges }}
  {{- $loadBalancerSourceRanges = . }}
{{- end }}
{{- $metadataLabelName := tpl ($currService.metadataLabelName | default $name) $root }}
{{- $selectorLabelName := tpl ($currService.selectorLabelName | default $name) $root }}
{{- $defaultSelectorLabels := true }}
{{- if and (or $currService.defaultSelectorLabels (eq ($currService.defaultSelectorLabels | toString) "false")) (eq (kindOf $currService.defaultSelectorLabels) "bool") }}
  {{- $defaultSelectorLabels = $currService.defaultSelectorLabels }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  namespace: {{ $namespace }}
  labels:
    {{- range $currPort := get $ports "ports" }}
      {{- if or (eq $currPort.name "metrics-prom")  (eq $currPort.name "http-actuator")}}
    k8sexporter:  "true" 
      {{- end }}
    {{- end }}
{{- include "radcom.labels" $root | nindent 4 }}
{{- include "radcom.selectorLabels" (dict "root" $root "name" $metadataLabelName) | nindent 4 }}
  {{- with $root.Values.podAdditionalLabels }}
    {{- tpl (toYaml .) $root | nindent 4 }}
  {{- end }}
  {{- with $serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $serviceType }}
  {{- if $currService.clusterIP }}
  {{- with $currService.clusterIP }}
  clusterIP: {{ tpl . $root }}
  {{- end }}
  {{- end }}
  ports:
    {{- range $currPort := get $ports "ports" }}
    - port: {{ get $currPort "port" | default 80 }}
      targetPort: {{ get $currPort "targetPort" | default 8080 }}
      name: {{ tpl ($currPort.name | default "http") $root | trunc 15 }}
      protocol: {{ $currPort.protocol | default "TCP" }}
      {{- if or (eq $serviceType "NodePort")  (eq $serviceType "LoadBalancer")}}
      {{- if eq (kindOf $currPort.nodePort) "string" }}
      {{- with $currPort.nodePort }}
        {{- $nodePort = tpl . $root }}
      {{- end }}
      {{- else}}
      {{- with $currPort.nodePort }}
        {{- $nodePort = . }}
      {{- end }}
      {{- end }}
      {{- if $nodePort }}
      nodePort: {{ $nodePort }}
      {{- $nodePort = "" }}
      {{- end }}
      {{- end }}
    {{- end }}
  {{- with $loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- if $currService.externalTrafficPolicy }}
  externalTrafficPolicy: {{ $currService.externalTrafficPolicy }}
  {{- end }}
  {{- if $currService.sessionAffinity }}
  sessionAffinity: {{ $currService.sessionAffinity }}
  {{- end }}
  selector:
  {{- if $defaultSelectorLabels }}
    {{- include "radcom.selectorLabels" (dict "root" $root "name" $selectorLabelName) | nindent 4 }}
  {{- else if not $defaultSelectorLabels }}
    {{- with $currService.selectorLabels }}
      {{- tpl (toYaml .) $root | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- with $root.Values.podAdditionalLabels }}
    {{- tpl (toYaml .) $root | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- define "radcom.services" }}
{{- template "radcom.merge" (append . "radcom.services.tpl") }}
{{- end }}
