application:
  name: "ace-cd"
  namespace: "production"
source:
  repoURL: "ssh://git@3.12.180.20/radcom/helmcharts.git"
  targetRevision: "master"
  path: "helmcharts/radcom/ace-cd"
deploy: "true"
cluster:
  provider: "gcp"
  region: "eitan"
  name: "gcp"
  environment: "rnd"
  project: "be"
  adress: "https://AC7149A00FBB8E4EFBC7B78C9318A9C5.gr7.us-east-2.eks.amazonaws.com"
