application:
  name: "monitoring-tools-cdf"
  namespace: "production"
target:
  targetRevision: "marian"
  path: "helmcharts/monitoring-tools-cdf"
deploy: false
cluster:
  name: cdf
  adress: "https://kubernetes.default.svc"