HELM_REGISTRY_PLACEHOLDER: &HELM_REGISTRY_PLACEHOLDER oci://us-south1-docker.pkg.dev/radcom-telus-poc-400307/eitan-test
apiVersion: v1
appVersion: '1.0'
dependencies:
- name: cs-analyzer-infra
  repository: *HELM_REGISTRY_PLACEHOLDER
  version: 1.446.45
- name: shared-templates
  repository: *HELM_REGISTRY_PLACEHOLDER
  version: 1.0.0
description: bp-analyzer-infra
name: cs-analyzer-infra
version: 13.11.19