application:
  ignoreDifferences:
    - group: 'kubevirt.io/v1'
      kind: VirtualMachine
      jsonPointers:
      - /spec
    - group: 'v1'
      kind: Service
      jsonPointers:
      - /spec
  name: "vertica"
  namespace: "default"
target:
  targetRevision: "eitan"
  path: "vms_argo/helmcharts/Vertica"
deploy: true
cluster:
  name: in-cluster
  address: "https://kubernetes.default.svc"
