apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "argocd-server-tls"
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: "global-secret-store"
    kind: ClusterSecretStore
  target:
    name: "argocd-server-tls"
    creationPolicy: Owner
  data:
    - secretKey: "tls.crt"
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: Base64
        key: "k0s-tools/certificates/star-radcom.co.il"
        metadataPolicy: None
        property: "tls.crt"
    - secretKey: "tls.key"
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: Base64
        key: "k0s-tools/certificates/star-radcom.co.il"
        metadataPolicy: None
        property: "tls.key"
