HELM_REGISTRY_PLACEHOLDER: &HELM_REGISTRY_PLACEHOLDER oci://571789434150.dkr.ecr.us-east-2.amazonaws.com
apiVersion: v1
appVersion: '1.0'
description: ace-cd
name: ace-cd
version: 1.0.0
dependencies:
  - name: ace-cd-chart
    version: 1.12.0
    repository:  *HELM_REGISTRY_PLACEHOLDER
