{{- if .Values.add_blueprints }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-add-blueprint"
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-add-blueprint"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
      - name: add-blueprints-post-install-job
        image: "{{ .Values.global.docker_registry }}/ace-cd:{{ .Values.ace_cd_tag }}"
        #command: ["echo","post-install hook"]
        command: ["bash", "ps_tools/argocd/add_blueprints.sh"]
        env:
        - name: RADCOM_CONDUCTOR_IP
          valueFrom:
            configMapKeyRef:
              name: topology-config-map
              key: conductor_ip
        - name: DEPLOYMENTNAME
          value: {{ .Release.Name }}
        - name: RADCOM_REVISION
          value: "{{ .Release.Revision }}"
        - name: RADCOM_VERSION
          value: "{{ .Chart.Version }}"
        - name: RADCOM_APPNAME
          value: "{{ .Chart.Name }}"
        volumeMounts:
        - name: values-volume
          mountPath: /values
      volumes:
      - name: values-volume
        configMap:
          name: values-cm
{{ end }}
