{{- if .Values.wait_for_event_bus }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-wait-event-bus-pre-hook"
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-wait-event-bus-pre-hook"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      restartPolicy: Never
      containers:
      - name: wait-event-bus-pre-install-job
        image: "{{ .Values.global.docker_registry }}/ace-cd:{{ .Values.ace_cd_tag }}"
        command: ["bash", "ps_tools/argocd/wait_for_event_bus.sh"]
{{ end }}

