apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "nexus-credentials"
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: "global-secret-store"
    kind: ClusterSecretStore
  target:
    name: "nexus-credentials"
    creationPolicy: Owner
  data:
    - secretKey: user
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "k0s-tools/nexus/credentials"
        metadataPolicy: None
        property: user
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "k0s-tools/nexus/credentials"
        metadataPolicy: None
        property: password
