HELM_REGISTRY_PLACEHOLDER: &HELM_REGISTRY_PLACEHOLDER oci://692859913461.dkr.ecr.us-east-2.amazonaws.com
apiVersion: v1
appVersion: '1.0'
dependencies:
- name: cs-online-db
  repository: *HELM_REGISTRY_PLACEHOLDER
  version: 1.67.0
- name: shared-templates
  version: 1.11.1
  repository: file://../../radcom/shared-templates
description: online-db
name: -online-db
version: 14.01.04
