{{- define "radcom.accountRole.tpl" }}
  {{- $enabled := true }}
  {{- if eq (kindOf .Values.enabled) "bool"  }}
  {{-   $enabled = .Values.enabled }}
  {{- end }}
  {{- if $enabled }}
{{- $myVer := .Capabilities.KubeVersion.GitVersion}}
{{- if semverCompare ">=1.19.0" $myVer -}}
apiVersion: rbac.authorization.k8s.io/v1
{{- else -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}

kind: ClusterRole
metadata:
  name: {{ include "radcom.serviceAccountName" . }}
rules:
  {{- if .Values.accountRole }}
  {{- with .Values.accountRole.apiGroups }}
  - apiGroups:
    {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- with .Values.accountRole.resources }}
    resources:
    {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- with .Values.accountRole.verbs }}
    verbs:
  {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- define "radcom.accountRole" -}}
  {{- template "radcom.merge" (append . "radcom.accountRole.tpl") -}}
  {{- end -}}
