{{- define "radcom.crd.tpl" -}}
{{- $enabled := true }}
{{- if eq (kindOf .Values.enabled) "bool"  }}
  {{- $enabled = .Values.enabled }}
{{- end }}
{{- if $enabled }}
{{- $root := . }}
{{- $namespace := "production" }}
{{- if $root.Values.global }}
  {{- with $root.Values.global.namespace }}
    {{- $namespace = . }}
  {{- end }}
{{- end }}
{{- $apiVersion := "topology.radcom.com/v1" }}
{{- if not (.Capabilities.APIVersions.Has $apiVersion) -}}
{{- range $crd := .Values.crds }}
{{- $singularName := "" }}
{{- with $crd.singularName }}
  {{- $singularName = . }}
{{- end }}
{{- $pluralName := "" }}
{{- with $crd.pluralName }}
  {{- $pluralName = . }}
{{- end }}
{{- $kind := "" }}
{{- with $crd.kind }}
  {{- $kind = . }}
{{- end }}
{{- $group := "" }}
{{- with $crd.group }}
  {{- $group = . }}
{{- end }}
{{- $servedFlag := true }}
{{- if and (not $crd.servedFlag) (eq ($crd.servedFlag | toString) "false") }}
  {{- $servedFlag = $crd.servedFlag }}
{{- else if $crd.servedFlag }}
  {{- $servedFlag = $crd.servedFlag }}
{{- end }}
{{- $storageFlag := true }}
{{- if and (not $crd.storageFlag) (eq ($crd.storageFlag | toString) "false") }}
  {{- $storageFlag = $crd.storageFlag }}
{{- else if $crd.storageFlag }}
  {{- $storageFlag = $crd.storageFlag }}
{{- end }}

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: {{ $pluralName }}.{{ $group }}
spec:
  group: {{ $group }}
  versions:
    - name: v1
      served: {{ $servedFlag }}
      storage: {{ $storageFlag }}
{{- with $crd.path }}
      schema: {{ tpl ($.Files.Get (printf "%s" .)) $root | nindent 8 }}
{{- end }}
{{- with $crd.additionalPrinterColumns }}
      additionalPrinterColumns: {{ toYaml . | nindent 8 }}
{{- end }}
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: {{ $pluralName }}
    # singular name to be used as an alias on the CLI and for display
    singular: {{ $singularName }}
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: {{ $kind }}
    # shortNames allow shorter string to match your resource on the CLI
{{- with $crd.shortNames }}
    shortNames: {{ toYaml . | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- define "radcom.crd" -}}
{{- template "radcom.merge" (append . "radcom.crd.tpl") -}}
{{- end -}}