{{- define "radcom.ingress.tpl" }}
{{- $enabled := true }}
{{- if eq (kindOf .Values.enabled) "bool"  }}
{{-   $enabled = .Values.enabled }}
{{- end }}
{{- if $enabled }}
{{- if .Values.ingresses }}
{{- $namespace := "production" }}
{{- if .Values.global }}
  {{- with .Values.global.namespace }}
    {{- $namespace = . }}
  {{- end }}
{{- end }}
{{- $root := . -}}
{{- $fullName := include "radcom.fullname" . }}
{{- range $ingress := .Values.ingresses -}}
{{- $serviceName := (printf "%s-%s" $fullName "srv") }}
{{- if $ingress.serviceName }}
{{- $serviceName = tpl (toYaml $ingress.serviceName) $root }}
{{- end }}
{{- $servicePort := include "getServicePort" (list $root $serviceName) }}
{{- if $ingress.servicePort }}
{{- $servicePort = $ingress.servicePort }}
{{- end }}
{{- $host := "$http_host" }}
{{- if $ingress.reverseProxyIp }}
  {{- $host = tpl $ingress.reverseProxyIp $root }}
{{- end }}
{{- $ingressPath := tpl $ingress.path $root| default "/" }}
{{- $ingressPathType := $ingress.pathType | default "Prefix" }}
{{- $isAuthenticationmsAuth := false }}
{{- if $ingress.isAuthenticationmsAuth }}
{{- with $ingress.isAuthenticationmsAuth }}
    {{- $isAuthenticationmsAuth = tpl (toYaml .) $root }}
  {{- end }}
{{- if eq $isAuthenticationmsAuth "'false'"}}
{{- $isAuthenticationmsAuth = false }}
{{- else }}
{{- $isAuthenticationmsAuth = true }}
{{- end }}
{{- end }}

---
{{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ tpl $ingress.ingressName $root}}
  namespace: {{ $namespace }}
  {{- if $ingress.generation }}
  generation: {{ $ingress.generation }}
  {{- end }}
  {{- if $ingress.annotations }}
  annotations:
  {{- tpl (toYaml $ingress.annotations ) $root | nindent 4 }}
  {{- if $root.Values.maxFileUploadSize }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ $root.Values.maxFileUploadSize }}
    nginx.org/client-max-body-size: {{ $root.Values.maxFileUploadSize }}
  {{- end }}
  {{- if $isAuthenticationmsAuth }}
    nginx.ingress.kubernetes.io/auth-response-headers: iv-user, iv-groups, iv-remote-address
    nginx.ingress.kubernetes.io/auth-signin: https://{{ $host }}/authenticationms/?link=https://{{ $host }}/guardian/portal
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header iv-remote-address $remote_addr;
      proxy_set_header X-Real-IP $remote_addr;
      if ($http_cookie ~* "jwt=([^;]+)(?:;|$)") {
          set $token "$1";
      }
      proxy_set_header jwt $token;
    nginx.ingress.kubernetes.io/auth-url: http://authenticationms-srv.production.svc.cluster.local/api/v1/Authentication/authenticateToken
  {{- end }}
  {{- if $ingress.additionalAnnotations}}
    {{- include "getAdditionalAnnotations" (list  $root  $ingress.additionalAnnotations)| nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if $ingress.labels }}
    {{- with $ingress.labels }}
  labels:
      {{- tpl (toYaml .) $root | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if  $ingress.className}}
  ingressClassName: {{ $ingress.className }}
  {{- end }}
  tls:
    - hosts:
      - {{ $ingress.fqdn | default "kuberiq.com" }}
      secretName: {{ tpl $ingress.tls_secret $root| default "zeppelin-tls-secret" }}
  rules:
    - host: {{ $ingress.fqdn | default "kuberiq.com" }}
      http:
        paths:
          - backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $serviceName }}
                port: 
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
            {{- end }}
            path: {{ $ingressPath }}
            {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ $ingressPathType }}
            {{- end }}
    - http:
        paths:
          - backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $serviceName }}
                port: 
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
            {{- end }}
            path: {{ $ingressPath }}
            {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ $ingressPathType }}
            {{- end }}  
{{- end }}
{{ end }}
{{ end }}
{{ end }}
