{{- define "radcom.roleBinding.tpl" }}
  {{- $enabled := true }}
  {{- if eq (kindOf .Values.enabled) "bool"  }}
  {{-   $enabled = .Values.enabled }}
  {{- end }}
  {{- if $enabled }}

{{- $myVer := .Capabilities.KubeVersion.GitVersion}}
{{- if semverCompare ">=1.19.0" $myVer -}}
apiVersion: rbac.authorization.k8s.io/v1
{{- else -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
kind: ClusterRoleBinding
metadata:
  name: {{ include "radcom.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "radcom.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "radcom.fullname" . }}
    namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- end }}
  {{- define "radcom.roleBinding" -}}
  {{- template "radcom.merge" (append . "radcom.roleBinding.tpl") -}}
  {{- end -}}
