{{- define "radcom.serviceAccount.tpl" }}
{{- $enabled := true }}
{{- if eq (kindOf .Values.enabled) "bool"  }}
  {{- $enabled = .Values.enabled }}
{{- end }}
{{- if $enabled }}
{{- $root := . }}
{{- $name := include "radcom.name" $root }}
{{- $fullName := include "radcom.fullname" . }}
{{- $namespace := "production" }}
{{- if .Values.global }}
  {{- with .Values.global.namespace }}
    {{- $namespace = . }}
  {{- end }}
{{- end }}
{{- range $serviceAccount := .Values.servicesAccount }}
{{- $metadataLabelName := $serviceAccount.metadataLabelName | default $name }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "radcom.serviceAccountName" (dict "root" $root "serviceAccount" $serviceAccount.serviceAccount) }}
  namespace: {{ $namespace }}
  labels:
{{- include "radcom.labels" $root | nindent 4 }}
{{- include "radcom.selectorLabels" (dict "root" $root "name" $metadataLabelName) | nindent 4 }}
{{- with $serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- define "radcom.serviceAccount" -}}
{{- template "radcom.merge" (append . "radcom.serviceAccount.tpl") -}}
{{- end -}}