application:
  name: "k8s-infra"
  namespace: "default"
target:
  targetRevision: "eitan"
  path: "containters/helmcharts/k8s-infra"
deploy: true
cluster:
  name: in-cluster
  adress: "https://kubernetes.default.svc"
