application:
  name: "aim"
  namespace: "default"
target:
  targetRevision: "eitan"
  path: "containters/helmcharts/bp-aim"
deploy: true
cluster:
  name: in-cluster
  adress: "https://kubernetes.default.svc"
