apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "renovate-env"
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: "global-secret-store"
    kind: ClusterSecretStore
  target:
    name: "renovate-env"
    creationPolicy: Owner
  data:
    - secretKey: RENOVATE_PLATFORM
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "k0s-tools/renovate/renovate-env"
        metadataPolicy: None
        property: RENOVATE_PLATFORM
    - secretKey: RENOVATE_ENDPOINT
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "k0s-tools/renovate/renovate-env"
        metadataPolicy: None
        property: RENOVATE_ENDPOINT
    - secretKey: RENOVATE_GIT_FS
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "k0s-tools/renovate/renovate-env"
        metadataPolicy: None
        property: RENOVATE_GIT_FS
    - secretKey: RENOVATE_USERNAME
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "k0s-tools/renovate/renovate-env"
        metadataPolicy: None
        property: RENOVATE_USERNAME
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "k0s-tools/renovate/renovate-env"
        metadataPolicy: None
        property: RENOVATE_PASSWORD
    - secretKey: NEXUS_USER
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "k0s-tools/renovate/renovate-env"
        metadataPolicy: None
        property: NEXUS_USER
    - secretKey: NEXUS_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "k0s-tools/renovate/renovate-env"
        metadataPolicy: None
        property: NEXUS_PASSWORD
    - secretKey: DOCKER_HUB_USERNAME
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "k0s-tools/renovate/renovate-env"
        metadataPolicy: None
        property: DOCKER_HUB_USERNAME
    - secretKey: DOCKER_HUB_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "k0s-tools/renovate/renovate-env"
        metadataPolicy: None
        property: DOCKER_HUB_PASSWORD
    - secretKey: GITHUB_COM_TOKEN
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "k0s-tools/renovate/renovate-env"
        metadataPolicy: None
        property: GITHUB_COM_TOKEN
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "k0s-tools/renovate/renovate-env"
        metadataPolicy: None
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "k0s-tools/renovate/renovate-env"
        metadataPolicy: None
        property: AWS_SECRET_ACCESS_KEY
