application:
  name: "network-analytics"
  namespace: "production"
target:
  targetRevision: "marian"
  path: "helmcharts/network-analytics"
deploy: false
cluster:
  name: cdf
  adress: "https://kubernetes.default.svc"