BLUEPRINT_RAN_PROBE_B: &BLUEPRINT_RAN_PROBE_B "100"
CONDUCTOR_VIP_PLACEHOLDER: &CONDUCTOR_VIP_PLACEHOLDER internal-argocd14RadcomBEALB-783104905.us-east-2.elb.amazonaws.com
DOCKER_REGISTRY: &DOCKER_REGISTRY 692859913461.dkr.ecr.us-east-2.amazonaws.com
MONGO_IP: &MONGO_IP "10.8.33.203"
QROUTER_IP: &QROUTER_IP "10.8.33.247"
SITE_PLACEHOLDER: &SITE_PLACEHOLDER jerus
NAMESPACE: &NAMESPACE production
CLOUD: &CLOUD aws
VERSION: &VERSION 14.01.00.000.04

cs-ran:
  ran-core-ms-chart:
    configMap:
      conductorIp: *CONDUCTOR_VIP_PLACEHOLDER
      mongoIp: *MONGO_IP
      qrouterIps: *QROUTER_IP
      siteName: *SITE_PLACEHOLDER